### ISSUE TITLE
pg_dump 10.3 - всегда предваряет имя объекта именем схемы

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#10]
Коллеги, начиная с 10.3 pg_dump теперь всегда предваряет имя объекта именем схемы. Таким образом внутри дампа нет теперь переключений путей поиска. Очень бы хотелось и внутри проекта не иметь таких команд: 
SET search_path = bankrupt, pg_catalog;
Конечно если у человека всего 1 схема, то так сказать чертеж замутняется при этом, но вот если схем много... то это уже насущная необходимость.
Хотелось бы иметь флажок который вводил бы новый синтаксис, такой как в pg_dump 10.3

**Comment by AXEPOH** [comment]
Добавлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/19f05edb1665ca9424a89c7e0e5994729fba2fc8
