### ISSUE TITLE
Изменение порядка колонок в типе - компаратор не генерирует пересоздание типа

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#100]
Добрый день,

Использую последнюю версию pgcodekeeeper - 7.5.0
В моём проекте сильное использование объектов `TYPE`
Обратил внимание, что сейчас если поменять порядок колонок в типе, то компаратор ничего не генерирует.
Это очень важная для меня часть, так как типы имеют сильную зависимость от других объектов.
Прошу вас добавить пересоздание типа в случае расхождения порядка следования колонок.

Спасибо!

**Comment by AXEPOH** [comment]
исправлено в dd1e8578a3a723c6d9047904f53cb8b8292415d2
