### ISSUE TITLE
Представления и режим "Печатать DROP перед CREATE Конструкцией"

### ISSUE THREAD

**Issue by Fenoman** [pgcodekeeper/pgcodekeeper#102]
Представим, что у нас есть такое представление:

```plpgsql
CREATE VIEW dummy_tmp.test_view AS
	SELECT 1 AS column1;
```
Оно существует как в базе, так и в проекте.

Теперь меняем его в проекте:
```plpgsql
CREATE VIEW dummy_tmp.test_view AS
	SELECT 2 AS column1;
```
Генерируем скрипт со следующими настройками:
![image](https://github.com/pgcodekeeper/pgcodekeeper/assets/34582446/e0d38681-0c87-412f-a097-0e87f90230dc)

На выходе получаем такой скрипт:
```plpgsql
SET TIMEZONE TO 'Europe/Moscow';

START TRANSACTION;

SET search_path = pg_catalog;

DROP VIEW IF EXISTS dummy_tmp.test_view;

DROP VIEW IF EXISTS dummy_tmp.test_view;

CREATE VIEW dummy_tmp.test_view AS
	SELECT 2 AS column1;

COMMIT TRANSACTION;
```

Вопрос, почему генерируется ДВА удаления? Ошибкой, конечно,  это не является и скрипт применится успешно. Однако, возможно это "вскроет" некоторые другие проблемы?

Подозреваю, что проблема кроется в анализе зависимостей и построения правильной миграционной последовательности применения. Если создать родительское представление, а затем изменить подчиненное - получаем такой скрипт:
```plpgsql
SET TIMEZONE TO 'Europe/Moscow';

START TRANSACTION;

SET search_path = pg_catalog;

-- DEPCY: This VIEW depends on the VIEW: dummy_tmp.test_view_child

DROP VIEW IF EXISTS dummy_tmp.test_view_parent;

DROP VIEW IF EXISTS dummy_tmp.test_view_child;

-- DEPCY: This VIEW is a dependency of VIEW: dummy_tmp.test_view_parent

DROP VIEW IF EXISTS dummy_tmp.test_view_child;

CREATE VIEW dummy_tmp.test_view_child AS
	SELECT 2 AS column1;

DROP VIEW IF EXISTS dummy_tmp.test_view_parent;

CREATE VIEW dummy_tmp.test_view_parent AS
	SELECT 1 AS column1,
    2 AS column2,
    t.column1 AS column3
   FROM dummy_tmp.test_view_child t;

COMMIT TRANSACTION;
``` 

Видим ДВА удаления подряд в начале, и затем еще по одному перед каждым созданием представлений.

Если такое поведение является валидным - без проблем, можно закрывать issue.

**Comment by AXEPOH** [comment]
При включенной настройке, не проверяется наличие удаления в скрипте, посмотрим, что можно сделать.

**Comment by Fenoman** [comment]
Спасибо! Но приоритет, можно сказать, самый низкий у этого issue) На "скорость полета" это не влияет. Если исправление повлечет за собой масштабные модификации - точно того не стоит.

**Comment by AXEPOH** [comment]
Как показывает практика - среднее выполнение issue ~ 3 лет)

**Comment by Fenoman** [comment]
Все, что меньше вечности - уже хорошо! )

**Comment by AXEPOH** [comment]
исправлено в a48f06fc79bff8a1f00ebde17a2f913259b05b9e

**Comment by Fenoman** [comment]
Великолепно!)
