### ISSUE TITLE
PK, FK и последовательности в режиме "Печатать CREATE IF NOT EXISTS / DROP IF EXISTS"

### ISSUE THREAD

**Issue by Fenoman** [pgcodekeeper/pgcodekeeper#103]
Во-первых, спасибо за этот режим - он максимально полезный! Бесполезно бороться с людьми, которые создают объекты на боевых базах (таблицы особенно) в "пожарном" режиме, когда нужно здесь и сейчас, а ждать сборки обновления и его раскатки N кол-во минут "это очень долго". Ваш инструмент органично встроен в наш Pipeline сборки и ничего кроме восторга не вызывает (особенно по сравнению с SSDT от Microsoft для MSSQL). А как известно если нельзя что-то победить - надо это возглавить. Так вот, для счастья не хватает нескольких вещей...

Представим себе такой файл в проекте, определение таблицы `dummy_tmp.temp_test` :
```plpgsql
CREATE TABLE dummy_tmp.temp_test (
	id integer NOT NULL,
	column1 int
);

ALTER TABLE dummy_tmp.temp_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME dummy_tmp.temp_test_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

--------------------------------------------------------------------------------

CREATE INDEX temp_test_column1_idx ON dummy_tmp.temp_test USING btree (column1);

--------------------------------------------------------------------------------

CREATE TRIGGER some_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON dummy_tmp.temp_test
	FOR EACH STATEMENT
	EXECUTE PROCEDURE dummy_tmp.trigger_disable_dml();

--------------------------------------------------------------------------------

ALTER TABLE dummy_tmp.temp_test
	ADD CONSTRAINT temp_test_pkey PRIMARY KEY (id)
	USING INDEX TABLESPACE ts_tmp;

--------------------------------------------------------------------------------

ALTER TABLE dummy_tmp.temp_test
	ADD CONSTRAINT fk_test FOREIGN KEY (column1) REFERENCES dummy_tmp.temp_test_fk(id) DEFERRABLE;

```
Ушлый разработчик уже применил его на какой-то из продуктовых базах из-под палок руководителя проекта, чтобы потушить пятую точку заказчика набирающего уже первую космическую скорость...

Через время собирается обновление через Pipeline и еще через время применяется на различные продуктовые базы, включая ту, на которой "все горело". Миграционный скрипт генерируется со следующими настройками:
![image](https://github.com/pgcodekeeper/pgcodekeeper/assets/34582446/39a8c538-fcd7-45c5-92bd-ded48789b454)

Получаем следующий миграционный скрипт:
```plpgsql
SET TIMEZONE TO 'Europe/Moscow';

START TRANSACTION;

SET search_path = pg_catalog;

CREATE TABLE IF NOT EXISTS dummy_tmp.temp_test (
	id integer NOT NULL,
	column1 integer
);

ALTER TABLE dummy_tmp.temp_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
	SEQUENCE NAME dummy_tmp.temp_test_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

CREATE INDEX IF NOT EXISTS temp_test_column1_idx ON dummy_tmp.temp_test USING btree (column1);

ALTER TABLE dummy_tmp.temp_test
	ADD CONSTRAINT temp_test_pkey PRIMARY KEY (id)
	USING INDEX TABLESPACE ts_tmp;

ALTER TABLE dummy_tmp.temp_test
	ADD CONSTRAINT fk_test FOREIGN KEY (column1) REFERENCES dummy_tmp.temp_test_fk(id) DEFERRABLE;

DROP TRIGGER IF EXISTS some_trigger ON dummy_tmp.temp_test;

CREATE TRIGGER some_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON dummy_tmp.temp_test
	FOR EACH STATEMENT
	EXECUTE PROCEDURE dummy_tmp.trigger_disable_dml();

COMMIT TRANSACTION;
```

Все хорошо с...
- таблицей - если она есть на целевой базе, то не создается
- индексом - если они есть на целевой базе, то не создаются
- триггерами - просто будет их пересоздание

Плохо с...
- последовательности - скрипт валится, так как такая последовательность уже есть в базе
- первичными ключами - скрипт валится, так как PK уже есть в целевой базе
- внешними ключами - скрипт валится, такая FK уже есть в целевой базе

К сожалению никаких встроенных механизмов у Postgres для этих случаев нет, чтобы проверить существование этих объектов придется лезть в системный каталог. Отсюда вопрос, возможно ли реализовать вот такую схему генерации скриптов для этих объектов в режиме "Печатать CREATE IF NOT EXISTS / DROP IF EXISTS":
```plpgsql
SET TIMEZONE TO 'Europe/Moscow';

START TRANSACTION;

SET search_path = pg_catalog;

CREATE TABLE IF NOT EXISTS dummy_tmp.temp_test (
	id integer NOT NULL,
	column1 integer
);

-- Проверка существования последовательности привязанной к колонке через GENERATED конструкцию (SERIAL мы не применяем)
DO
$seq$
BEGIN
    IF NOT EXISTS (
                      SELECT
                          1
                      FROM pg_catalog.pg_class pc
                           INNER JOIN pg_catalog.pg_namespace AS pn
                                      ON pn.oid = pc.relnamespace
                           INNER JOIN pg_catalog.pg_depend pd
                                      ON pd.objid = pc.oid
                           INNER JOIN pg_catalog.pg_class p_table
                                      ON p_table.oid = pd.refobjid
                           INNER JOIN pg_catalog.pg_namespace AS pn_table
                                      ON pn_table.oid = p_table.relnamespace
                           INNER JOIN pg_catalog.pg_attribute attr
                                      ON attr.attrelid = p_table.oid
                      WHERE pc.relname = 'temp_test_id_seq' -- имя последовательности
                        AND pn.nspname = 'dummy_tmp'        -- схема последовательности
                        AND p_table.relname = 'temp_test'   -- имя таблицы
                        AND pn_table.nspname = 'dummy_tmp'  -- схема таблицы
                        AND attr.attname = 'id' -- имя столбца
                  )
    THEN
        ALTER TABLE dummy_tmp.temp_test ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME dummy_tmp.temp_test_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MAXVALUE
            NO MINVALUE
            CACHE 1
        );
    END IF;
END
$seq$;

CREATE INDEX IF NOT EXISTS temp_test_column1_idx ON dummy_tmp.temp_test USING btree (column1);

-- Проверка существования PK
DO
$pk$
BEGIN
    IF NOT EXISTS(
                     SELECT
                         1
                     FROM information_schema.table_constraints TC
                     WHERE TC.table_schema = 'dummy_tmp' -- схема таблицы
                       AND TC.table_name = 'temp_test'   -- имя таблицы
                       AND TC.constraint_name = 'temp_test_pkey' -- имя PK
                 )
    THEN 
        ALTER TABLE dummy_tmp.temp_test
            ADD CONSTRAINT temp_test_pkey
            PRIMARY KEY (id) USING INDEX TABLESPACE ts_tmp;
    END IF;
END
$pk$;

-- Проверка существования FK (точно также как и PK)
DO
$pk$
BEGIN
    IF NOT EXISTS(
                     SELECT
                         1
                     FROM information_schema.table_constraints TC
                     WHERE TC.table_schema = 'dummy_tmp' -- схема таблицы
                       AND TC.table_name = 'temp_test'   -- имя таблицы
                       AND TC.constraint_name = 'fk_test' -- имя FK
                 )
    THEN 
        ALTER TABLE dummy_tmp.temp_test
	        ADD CONSTRAINT fk_test FOREIGN KEY (column1) REFERENCES dummy_tmp.temp_test_fk(id) DEFERRABLE;
    END IF;
END
$pk$;

DROP TRIGGER IF EXISTS some_trigger ON dummy_tmp.temp_test;

CREATE TRIGGER some_trigger
	BEFORE INSERT OR UPDATE OR DELETE ON dummy_tmp.temp_test
	FOR EACH STATEMENT
	EXECUTE PROCEDURE dummy_tmp.trigger_disable_dml();

COMMIT TRANSACTION;
```
Данный скрипт корректно применится в обоих случаях. 

Конечно стоить понимать, что таком случае может возникнуть такое явление как "дрифтинг":
* если PK создан в другом табличном пространстве на целевой базе - так и останется
* если последовательность создана с другими параметрами на целевой базе (начальный сид, инкремент...) - так и останется
* если ограничение создано с другими параметрами (например без DEFERRABLE) - так и останется

Но такие ситуации довольно редки и выявляются периодическими инспекциями через определенные интервалы времени, так что ничего страшного в этом нет. Например, даже таблица в целевой базе может быть создана с другим табличным пространством или параметром FILLFACTOR и `CREATE TABLE IF NOT EXISTS` это "пропустит" - ничего в этом критического нет. 

ГОРАЗДО важнее не разбираться каждый раз с миграционными скриптами, а проводить периодические и ЗАПЛАНИРОВАННЫЕ инспекции устраняя "дрифтинг".

Заране спасибо за любую реакцию на этот issue какой бы она ни была!

**Comment by AXEPOH** [comment]
Надо подумать)

**Comment by Fenoman** [comment]
Хороший вариант. Вопросов нет!

**Comment by AXEPOH** [comment]
Займемся тогда в ближайшее время

**Comment by AXEPOH** [comment]
Добавлено в 6eb0fe572aa34e5234866a280ce05d1061618356

**Comment by AxelCat** [comment]
добавили в релиз https://github.com/pgcodekeeper/pgcodekeeper/blob/master/CHANGELOG.md#940---2024-03-05

**Comment by Fenoman** [comment]
Да, уже проверили! Идеально!
