### ISSUE TITLE
CLUSTER ... USING PK - компаратор не видит таких возможностей

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#104]
Добрый день,

Попробовал использовать кластеризацию таблиц в деле.
Оказалось, что pgcodekeeper не умеет обнаруживать кластеризацию таблиц с использованием ограничения первичного ключа.
Пример:
```
CREATE TABLE public.t_test (
	contact_id 	bigint NOT NULL,
	src_system_id 	bigint NOT NULL,
	load_id 		bigint NOT NULL
);

CREATE INDEX t_test_idx ON public.t_test USING btree (load_id);

ALTER TABLE public.t_test
	ADD CONSTRAINT t_test_pkey PRIMARY KEY (contact_id);
```
теперь если в БД выполнить команду:
```
cluster public.t_test using t_test_pkey;
```
и сравнить компаратором, то изменений обнаружено не будет.

изменим кластеризацию на простой индекс:
```
cluster public.t_test using t_test_idx;
```
теперь изменения в кластеризации таблицы будут обнаружены.

Также, если попробовать в описании таблицы pgcodekeeper самому написать:
```
ALTER TABLE public.t_test CLUSTER ON t_test_pkey;
```
то кипер такой код пометит как ошибочный, так как не сможет найти нужный объект (ищет строго индекс?).

**Comment by AXEPOH** [comment]
Добавлено в 217067bb843084f6ac744d9e99bfacd5f8fdd429
