### ISSUE TITLE
MSSQL: CONSTRAINT во временной таблице или табличной переменной

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#106]
Если в теле функции, процедуры объявлен индекс / первичный ключ - CONSTRAINT, то после парсинга pgCodeKeeper указывает на ошибку
Например: CREATE TABLE #calendar (date DATETIME PRIMARY KEY CLUSTERED (date));

Обходное решение: разделить индекс / первичный ключ - CONSTRAINT запятой
Например: CREATE TABLE #calendar (date DATETIME, PRIMARY KEY CLUSTERED (date));

Артефакты: https://drive.google.com/drive/folders/1ExlFdsiwN-AGZ6Dgs9GrP2_5Zq44KFwa

**Comment by AXEPOH** [comment]
Исправлено в 5b57ece83f8dd74206bc65dbd889cf495471ebf0
