### ISSUE TITLE
MSSQL: NULL-значения в входных параметрах объекта

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#107]
Если в входных параметрах объекта есть входные переменные, поддерживающие NULL значения, то pgCodeKeeper указывает на ошибку
Например: @firmId INT NULL

Обходное решение: инициализация входных параметров NULL-значениями
Например: @firmId INT = NULL

Артефакты: https://drive.google.com/drive/folders/1FgKMwo0pcnfrI9Y_bWi5QKKKtI5gDq_C

**Comment by AXEPOH** [comment]
Исправлено в f9b7fa6e6450ea4206ca831840ae3c13482d1568
