### ISSUE TITLE
MSSQL: SET TRAN ISOLATION LEVEL READ UNCOMMITTED

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#108]
В процедуре указан уровень изоляции "SET TRAN ISOLATION LEVEL READ UNCOMMITTED;", то pgCodeKeeper видит в этом ошибку.
Обходное решение: указывать "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;"

Артефакты: https://drive.google.com/drive/folders/1sXyjsJajdKLw4YGr9n6BiS63T5ZUK4G_

**Comment by AXEPOH** [comment]
исправлено в 61536706368e0b8a8330dc092a41444d81e58bba
