### ISSUE TITLE
MSSQL: Неизвестная ошибка из-за которой обрезается тело процедуры

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#110]
Неизвестная ошибка, которую подсвечивает pgCodeKeeper, из-за которой тело объекта обрезалось. Отсутствует END в конце процедуры

Артефакты: https://drive.google.com/drive/folders/1HXGhDMvC0NKjcISz_zYFuz4cdBrtx9FQ

**Comment by AXEPOH** [comment]
В примере (before parse) на 13 и 71 строке находиться символ (`\u200b`), что и "убило" парсер

**Comment by KittyNicky** [comment]
Интересный кейс, проверил, все так, спасибо!
Такой кейс не будете править? Закрыть задачу?

**Comment by AXEPOH** [comment]
Надо подумать)

**Comment by AXEPOH** [comment]
Исправлено в c2d5cf85f1ecc2d55549281699b7373c0f2b04a0
