### ISSUE TITLE
MSSQL: DECLARE CURSOR FOR

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#111]
Проблема найдена в системной процедуре
Если объявлен курсор с дополнительным параметром for update of, то pgCodeKeeper видит в этом ошибку, обрезая процедуру (отсутствует END в конце процедуры)

Артефакты: https://drive.google.com/drive/folders/1rjKcct0fNPoZXaRsTtEBVgMov-zSdX83

**Comment by AXEPOH** [comment]
исправлено в 61536706368e0b8a8330dc092a41444d81e58bba
