### ISSUE TITLE
MSSQL: GETDATE-значения в входных параметрах объекта

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#112]
Если в входных параметрах объекта есть переменные, которые инициализируются значениями GETDATE, то pgCodeKeeper видит в этом ошибку и обрезает процедуру

Артефакты: https://drive.google.com/drive/folders/1KHXM_RaBmnq9EmZfc552MuFQEWWOOF2f

**Comment by AXEPOH** [comment]
Исправлено в 7564adc481fc5ece9f4d164be1f577cf83429617
