### ISSUE TITLE
MSSQL: GROUP BY WITH

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#113]
Если в GROUP BY указаны дополнительные параметры WITH, например, "WITH ROLLUP", то pgCodeKeeper видит в этом ошибку и обрезает процедуру (не хватает END в конце)
Обходное решение: не писать WITH ROLLUP (но в данном случае он нужен)

Артефакты: https://drive.google.com/drive/folders/1TbyFNkSstNb1dxqSy-VhS7GeDv_GhKwP

**Comment by AXEPOH** [comment]
Исправлено в a04854df0c4edb43466ea8e6712f3f4a9ee2b6c0
