### ISSUE TITLE
MSSQL: OUTPUT CASE

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#114]
Если присутствует OUTPUT с конструкцией CASE, то pgCodeKeeper видит в этом ошибку и обрезает процедуру.

Артефакты: https://drive.google.com/drive/folders/1RIbpoRS1F-fWL9eohM5ZJq0LPq2htbmD

**Comment by AXEPOH** [comment]
Исправлено в 4689365433305fbb3dce4eacc71d0992202a3456
