### ISSUE TITLE
MSSQL: Поле INT IDENTITY с отрицательным диапазоном

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#115]
Если в таблице присутствует поле INT IDENTITY, начальное значение диапазона которого отрицательное (например, IDENTITY (-9999, 1)), то pgCodeKeeper видит в этом ошибку

Артефакты: https://drive.google.com/drive/folders/1SJTjHAeFkbHRo5BTxrCNyTorOZylWqW2

**Comment by AXEPOH** [comment]
Исправлено в 071353fc986f8b3fa0ef0862fe03e527bf7a5087
