### ISSUE TITLE
MSSQL: ALTER PARTITION FUNCTION

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#116]
Если в процедуре присутствует запросы, обслуживающие функции секционирования (ALTER PARTITION FUNCTION), то pgCodeKeeper видит в этом ошибку

Артефакты: https://drive.google.com/drive/folders/1AJqlo2v4xByl4ALnyPThpQT7c6EFLBiF

**Comment by AXEPOH** [comment]
исправлено в 61536706368e0b8a8330dc092a41444d81e58bba
