### ISSUE TITLE
MSSQL: EXECUTE AS LOGIN

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#117]
Если в процедуре есть команда "EXECUTE AS LOGIN", то pgCodeKeeper видит в этом ошибку

Артефакты: https://drive.google.com/drive/folders/1r1_rp_PVYaEpPO4Iyj36Zr4iJPCs_qhj

**Comment by AXEPOH** [comment]
Исправлено в f9b7fa6e6450ea4206ca831840ae3c13482d1568
