### ISSUE TITLE
MSSQL: FREETEXT

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#118]
Если в объекте используется встроенная функция FULLTEXT, то pgCodeKeeper видит её как ошибку

Артефакты: https://drive.google.com/drive/folders/18aZmzsNOApkNTVd4USjPCPRWcjp5Zv4h

**Comment by AXEPOH** [comment]
Исправлено в 8862f2fbb65f17e86c15beae051f96e9b1e1d54f
