### ISSUE TITLE
MSSQL: GRANT VIEW CHANGE TRACKING

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#119]
Если в схеме / таблице есть предоставление прав на отслеживание изменений пользователю, то pgCodeKeeper отмечает это как ошибку

Артефакты: https://drive.google.com/drive/folders/1Pa9hM330rWlbKkfB4t9UAY_RStUFi-ZR

**Comment by AXEPOH** [comment]
Исправлено в 071353fc986f8b3fa0ef0862fe03e527bf7a5087
