### ISSUE TITLE
MSSQL: TRUNCATE TABLE WITH PARTITION

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#120]
Если в процедуре присутствует запросы, обслуживающие секционированные таблицы, удаляя данные из секций (TRUNCATE TABLE WITH PARTITION), то pgCodeKeeper видит в этом ошибку

Артефакты: https://drive.google.com/drive/folders/17l_vS50JEgGTWezrKT4ywZSYNSTqtLck

**Comment by AXEPOH** [comment]
исправлено в 61536706368e0b8a8330dc092a41444d81e58bba
