### ISSUE TITLE
MSSQL: CONTAINS

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#121]
Если в процедуре используется встроенная функция CONTAINS, то pgCodeKeeper видит в этом ошибку

Артефакты: https://drive.google.com/drive/folders/1uP8bC1EzXjC2HT4-mUjdK_jxLsQxruWO

**Comment by AXEPOH** [comment]
Исправлено в 8862f2fbb65f17e86c15beae051f96e9b1e1d54f
