### ISSUE TITLE
MSSQL: Вложенные IF-конструкции

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#122]
В процедуре присутствуют вложенные IF-конструкции, в которые pgCodeKeeper видит ошибку

Артефакты: https://drive.google.com/drive/folders/1Gv46F1qC6B3mrST1HoWyebfKBWIT0LEW

**Comment by AXEPOH** [comment]
Не вижу проблем со вложенными IF, в примере парсер не смог правильно распарсить выражение из-за предыдущих ошибок.
