### ISSUE TITLE
PGSQL: MERGE INTO ... USING {string_to_table | json_to_recordset}

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#124]
Если в процедуре используется MERGE INTO ... USING {string_to_table | json_to_recordset}, то pgCodeKeeper видит в этом ошибку

Артефакты: https://drive.google.com/drive/folders/1-VT3uDraUJ2XZ_XLNckGhzby46In22IW?usp=sharing

**Comment by AXEPOH** [comment]
Исправлено в 9a6d4469b93b4c50eb4c042640dc33ddc81ee283
