### ISSUE TITLE
Ошибка при сравнении 2 баз PostgreSQL (16.0 vs 14.2)

### ISSUE THREAD

**Issue by dimahetman** [pgcodekeeper/pgcodekeeper#125]
Версия: 8.7.0, id сборки: 202309120748 для Windows 
есть 2 БД:

1. PostgreSQL 16.0 (Debian 16.0-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2. PostgreSQL 14.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4), 64-bit
при сранении струткур при помощи мастера -  получаю ошибку:  **cannot be cast to class**
удалил проект, попытался пересоздать получаю туже ошибку   **cannot be cast to class**
```
Ошибка инициализации проекта
IOException во время создания проекта: Ошибка при чтении схемы БД через JDBC, ошибка произошла при обработке jdbc:/crm_users_new/adm_event_log
class [Ljava.lang.Short; cannot be cast to class [Ljava.lang.Integer; ([Ljava.lang.Short; and [Ljava.lang.Integer; are in module java.base of loader 'bootstrap')
```
при этом 2 таблицы имеют идентичный DDL 

```
CREATE TABLE crm_users_new.adm_event_log (
	id bigserial NOT NULL,
	"type" varchar(50) NULL DEFAULT NULL::character varying,
	"date" timestamp NULL DEFAULT CURRENT_TIMESTAMP,
	id_user int4 NULL,
	"json" text NULL DEFAULT NULL::character varying,
	login varchar(50) NULL,
	message text NULL DEFAULT NULL::character varying,
	CONSTRAINT adm_event_log_pkey PRIMARY KEY (id),
	CONSTRAINT adm_user_fk FOREIGN KEY (id_user) REFERENCES crm_users_new.adm_user(id_user)
);
```

**Comment by AXEPOH** [comment]
Исправлено в версии 8.8.0 с добавление поддержки PostgreSQL 16.
