### ISSUE TITLE
Шаблоны

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#127]
Версия кипера 8.9.0 windows

1.
Если попробовать добавить шаблон, сохранить изменения и выйти, то при попытке открыть настройки получаем ошибку.
![изображение](https://github.com/pgcodekeeper/pgcodekeeper/assets/10084993/0e18607f-2756-4fb6-bc4e-21dc047767d4)

2.
Сейчас в списке шаблонов не отображается шаблон с контекстом для PostgreSQL для создания 
create procedure
create function 
хотя сами шаблоны есть в templates_pg.xml и они работают.

**Comment by AXEPOH** [comment]
Исправлено в 307ca7008b6dd633def0b52bfc3f149b77ec424c

**Comment by AXEPOH** [comment]
Исправление второго пункта 98d7c1459870c4f919ffc2441f4cd26c00f46e16
