### ISSUE TITLE
Информирование об ошибках в скрипте наката

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#13]
Коллеги, если в скрипте наката есть ошибка, то при выполнении появляется сообщение, что накат не удался и пишется позиция с ошибкой... но нет никакой информации ни о самой строке кода ни о номере строки....
С накатом и информированием что-то надо сделать. Сейчас слишком примитивно. Ошибки в большом скрипте искать трудно.
К примеру можно позиционироваться на нужную строку и подсветить проблемный участок.

**Comment by AXEPOH** [comment]
Добавлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/12c806a003b256022f648c73cc539a3818802252
