### ISSUE TITLE
MSSQL: Если изменяется поле, которое входит в индекс, то скрипт формируется без пересоздания зависимого индекса

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#130]
Если изменяется поле, которое входит в индекс, то скрипт формируется без пересоздания зависимого индекса

Проблема: на одном сервере поле name поддерживает NOT NULL значение, а на другом NULL. Необходимо обновить поле name с NULL на NOT NULL.

Исходная таблица и ее индекс:
```
CREATE TABLE dbo.test_table
    (id INT IDENTITY(1, 1) NOT NULL,
     name NVARCHAR(100) NULL,
     CONSTRAINT PK_test_table PRIMARY KEY CLUSTERED (id));
GO

CREATE NONCLUSTERED INDEX IX_test_table_name ON dbo.test_table (name)
GO
```

Скрипт, формируемый pgCodeKeeper при сравнении:
```
ALTER TABLE [dbo].[test_table]
	ALTER COLUMN [name] [nvarchar] (100) COLLATE Cyrillic_General_CI_AS NOT NULL
GO
```
Ошибки при выполнении скрипта:
Сообщение 5074, уровень 16, состояние 1, строка 25
индекс "IX_test_table_name" зависит от столбец "name".
Сообщение 4922, уровень 16, состояние 9, строка 25
Ошибка ALTER TABLE ALTER COLUMN name, так как один или несколько объектов обращаются к данному столбец.

Скрипт, который должен формироваться:
```
DROP INDEX [IX_test_table_name]
    ON [dbo].[test_table];
GO

ALTER TABLE [dbo].[test_table] ALTER COLUMN [name] NVARCHAR (100) NOT NULL;
GO

CREATE NONCLUSTERED INDEX [IX_test_table_name]
    ON [dbo].[test_table]([name] ASC);
GO

```

**Comment by AXEPOH** [comment]
Исправлено в a3387a22949180e5e7abd825485c99d204710ba3
