### ISSUE TITLE
MSSQL: При обновлении пользовательского типа данных не пересоздаются зависимые объекты

### ISSUE THREAD

**Issue by KittyNicky** [pgcodekeeper/pgcodekeeper#132]
Проблема: существует пользовательский тип данных, который необходимо обновить. На одном сервере внесены изменения в поле, которые необходимо накатить на другой сервер. Так же существует процедура, использующая этот пользовательский тип данных.

Исходная версия на одном сервере:
```
CREATE TYPE [dbo].[udtt_test] AS TABLE(
	[id] [int] NOT NULL,
	[name] [nvarchar] (100) COLLATE Cyrillic_General_CI_AS NOT NULL
)
GO
CREATE PROCEDURE [dbo].[test_procedure] @udtt udtt_test READONLY
WITH EXECUTE AS OWNER
AS
    BEGIN
        SET NOCOUNT ON;

        SELECT 1;
    END;
GO
```

Версия на другом сервере:
```
CREATE TYPE [dbo].[udtt_test] AS TABLE(
	[id] [int] NOT NULL,
	[name] [nvarchar] (300) COLLATE Cyrillic_General_CI_AS NULL
)
GO
CREATE PROCEDURE [dbo].[test_procedure] @udtt udtt_test READONLY
WITH EXECUTE AS OWNER
AS
    BEGIN
        SET NOCOUNT ON;

        SELECT 1;
    END;
GO
```

Скрипт, формируемый pgCodeKeeper:
```
DROP TYPE IF EXISTS [dbo].[udtt_test]
GO

CREATE TYPE [dbo].[udtt_test] AS TABLE(
	[id] [int] NOT NULL,
	[name] [nvarchar] (300) COLLATE Cyrillic_General_CI_AS NOT NULL
)
GO

```
Ошибки при выполнении скрипта:
Сообщение 3732, уровень 16, состояние 1, строка 4
Невозможно удалить тип "dbo.udtt_test", так как на него ссылается объект "test_procedure". Могут существовать другие объекты, которые ссылаются на этот тип.
Сообщение 219, уровень 16, состояние 1, строка 7
Тип "dbo.udtt_test" уже существует, или отсутствует разрешение на его создание.

Скрипт, который должен формироваться:
```
DROP PROCEDURE [dbo].[test_procedure];
GO

DROP TYPE [dbo].[udtt_test];
GO

CREATE TYPE [dbo].[udtt_test] AS TABLE (
    [id]   INT            NOT NULL,
    [name] NVARCHAR (300) NOT NULL);
GO

CREATE PROCEDURE dbo.test_procedure @udtt udtt_test READONLY
WITH EXECUTE AS OWNER
AS
    BEGIN
        SET NOCOUNT ON;

        SELECT 1;
    END;
GO
```

**Comment by KittyNicky** [comment]
Привет!
Уточните пожалуйста по проблеме, планируете ли вы её исправление?

**Comment by AXEPOH** [comment]
Да, когда-нибудь доберемся до нее

**Comment by AXEPOH** [comment]
тут проблема в том, что для пользовательских типов мы ожидаем имя схемы, в данном случае 

```
CREATE PROCEDURE dbo.test_procedure @udtt dbo.udtt_test READONLY
```

так как для MS SQL мы не храним списка всех системных типов и все что без схемы считается системным типом.

**Comment by KittyNicky** [comment]
Спасибо! Попробую с явным указанием схемы

**Comment by KittyNicky** [comment]
К сожалению, обходное решение с указанием схемы не сработало. 

Пример:
- На одном сервере:
```
CREATE TYPE [dbo].[udtt_test] AS TABLE(
	[id] [int] NOT NULL,
	[name] [nvarchar] (300) COLLATE Cyrillic_General_CI_AS NOT NULL
)
GO
CREATE PROCEDURE [dbo].[test_procedure] @udtt dbo.udtt_test READONLY
WITH EXECUTE AS OWNER
AS
    BEGIN
        SET NOCOUNT ON;

        SELECT 1;
    END;
GO
```
- На другом сервере:
```
CREATE TYPE [dbo].[udtt_test] AS TABLE(
	[id] [int] NOT NULL,
	[name] [nvarchar] (100) COLLATE Cyrillic_General_CI_AS NOT NULL
)
GO
CREATE PROCEDURE [dbo].[test_procedure] @udtt dbo.udtt_test READONLY
WITH EXECUTE AS OWNER
AS
    BEGIN
        SET NOCOUNT ON;

        SELECT 1;
    END;
GO
```

- Формируемый скрипт наката:
```
DROP TYPE IF EXISTS [dbo].[udtt_test]
GO

-- DEPCY: This TYPE is a dependency of PROCEDURE: [dbo].[test_procedure]

CREATE TYPE [dbo].[udtt_test] AS TABLE(
        [id] [int] NOT NULL,
        [name] [nvarchar] (300) COLLATE Cyrillic_General_CI_AS NOT NULL
)
GO
```
Зависимость определена, но в последовательности действий все равно не хватает пересоздания зависимых объектов

**Comment by AXEPOH** [comment]
Посмотрим, что можно сделать
