### ISSUE TITLE
Взаимоисключающие опции

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#137]
Уважаемые разработчики,

В desktop версии опции "печатать CREATE INDEX CONCURRENTLY" и "заключить скрипт наката в блок START TRANSACTION..." должны быть взаимоисключающими.

Попробовал использовать опцию генерации изменения индексов в конкурентном режиме.
Увидел отличный код. Вот только не учтено, что в режиме транзакции это сделать нельзя.
![изображение](https://github.com/pgcodekeeper/pgcodekeeper/assets/10084993/f94628f6-3134-4335-93fc-f8979ee45c1c)

Предлагаю, вам если ставится галочка
![изображение](https://github.com/pgcodekeeper/pgcodekeeper/assets/10084993/a9c71e65-9dbd-4b92-94b7-6116ac9bf323)
то обрамление транзакциями тогда убирать.

**Comment by AXEPOH** [comment]
Поправили в 30e6a128d5d26ef6e98b4417017881e125cfd2b6. Опция `печатать CREATE INDEX CONCURRENTLY` не будет работать вместе `заключить скрипт наката в блок START TRANSACTION...` для PostgreSQL. Дополнили описание настройки. 

![изображение](https://github.com/user-attachments/assets/36fe324c-482b-4f7e-9067-8d894e3ed787)
