### ISSUE TITLE
Нет сообщения что имя функции указано без схемы

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#14]
в папке схемы создал новую папку FUNCTION
вызвал контекстное меню и выбрал "Объект SQL"
в форме в окошко вбил имя функции (без схемы) и нажал Finish
и ничего не произошло... форма не закрылась хотя кнопка нажалась точно.
Указываю схему и снова нажимаю Finish - всё создается.

**Comment by AXEPOH** [comment]
Исправлено

https://github.com/pgcodekeeper/pgcodekeeper/commit/ba24b25bbbea0b10f88d028835f04296eb053faf

**Comment by sgrinko** [comment]
Спасибо!
