### ISSUE TITLE
Поддержка объекта расширенной статистики - CREATE STATISTICS

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#140]
Добрый день,

Обнаружил, что сейчас нет поддержки расширенной статистики
Оператор - CREATE STATISTICS
https://postgrespro.ru/docs/postgresql/16/sql-createstatistics
прошу добавить.
Может быть внутрь файла описания таблицы, так же как и индекс?

**Comment by AXEPOH** [comment]
Посмотрим

**Comment by AXEPOH** [comment]
добавлено в 4345a060912a8cf66ed6e03ba229dca6ae80699f
внутрь таблицы засунуть не получилось, так как объект можно создать в схеме, отличной от схемы таблицы

**Comment by sgrinko** [comment]
Спасибо!
