### ISSUE TITLE
Накат миграционного скрипта на GreenPlum

### ISSUE THREAD

**Issue by NickChadaev** [pgcodekeeper/pgcodekeeper#142]
GreenPlum 6.16.1 Postgrews 9.4.24  Выполнено сравнение проекта и БД, создан миграционный скрипт.

**Comment by NickChadaev** [comment]
Не создаются некоторые расширения из миграционного скрипта *(ниже приведён его текст:

SET check_function_bodies = false;

START TRANSACTION;
SET search_path = pg_catalog;

**СREATE EXTENSION IF NOT EXISTS citext SCHEMA public;      -- Первая ошибка
COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';**
-- -----------------------------------------------------------------------------------------------------------------------
-- ERROR: no pre-assigned OID for pg_type tuple "citext" (namespace:11 keyOid1:0 keyOid2:0) (oid_dispatch.c:650)  (seg1 10.219.66.151:6001 pid=23080) (oid_dispatch.c:650)
--  Line: 9
-- CREATE EXTENSION IF NOT EXISTS citext SCHEMA public
----------------------------------------------------

**CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public;         -- вторая ошибка
COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';**
-----------------------------------------------------------
-- ERROR: no pre-assigned OID for pg_proc tuple "digest" (namespace:11 keyOid1:0 keyOid2:0) (oid_dispatch.c:650)  (seg0 10.219.66.151:6000 pid=23932) (oid_dispatch.c:650)
--   Line: 17
-- CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public

ALTER TABLE public."UserRequisites_GP_test_part" SET WITH (REORGANIZE=true) DISTRIBUTED BY ("UserId");  --- !!!
ALTER TABLE public.pxf_ch_test_trg SET WITH (REORGANIZE=true) DISTRIBUTED BY ("EventDate");             --- !!!!
ALTER TABLE public.user_requisites_gp_test SET WITH (REORGANIZE=true) DISTRIBUTED BY ("UserId");        --- !!!

COMMIT TRANSACTION;

Будучи вынесенными в отдельный  скрипт, и другой инструмент (Dbeaver) операторы созвыполняются нормально.
Временное решение проблемы такое -  формировать миграционые скрипты в pgCodeKeeper, выполнять в другом инструменте.

**Comment by NickChadaev** [comment]
Не создаются некоторые расширения из миграционного скрипта (ниже приведён его текст:

SET check_function_bodies = false;
START TRANSACTION;
SET search_path = pg_catalog;

СREATE EXTENSION IF NOT EXISTS citext SCHEMA public;      -- Первая ошибка
COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings'; 
-- -----------------------------------------------------------------------------------------------------------------------
-- ERROR: no pre-assigned OID for pg_type tuple "citext" (namespace:11 keyOid1:0 keyOid2:0) (oid_dispatch.c:650)  (seg1 10.219.66.151:6001 pid=23080) (oid_dispatch.c:650)
--  Line: 9
-- CREATE EXTENSION IF NOT EXISTS citext SCHEMA public
----------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public;         -- вторая ошибка
COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
-----------------------------------------------------------
-- ERROR: no pre-assigned OID for pg_proc tuple "digest" (namespace:11 keyOid1:0 keyOid2:0) (oid_dispatch.c:650)  (seg0 10.219.66.151:6000 pid=23932) (oid_dispatch.c:650)
--   Line: 17
-- CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public
ALTER TABLE public."UserRequisites_GP_test_part" SET WITH (REORGANIZE=true) DISTRIBUTED BY ("UserId");  --- !!!
ALTER TABLE public.pxf_ch_test_trg SET WITH (REORGANIZE=true) DISTRIBUTED BY ("EventDate");             --- !!!!
ALTER TABLE public.user_requisites_gp_test SET WITH (REORGANIZE=true) DISTRIBUTED BY ("UserId");        --- !!!
COMMIT TRANSACTION;

Будучи вынесенными в отдельный  скрипт, и другой инструмент (Dbeaver) операторы созвыполняются нормально.
Временное решение проблемы такое -  формировать миграционые скрипты в pgCodeKeeper, выполнять в другом инструменте.

**Comment by NickChadaev** [comment]
Не создаются некоторые расширения из миграционного скрипта (ниже приведён его текст:

SET check_function_bodies = false;

START TRANSACTION;
SET search_path = pg_catalog;

CREATE EXTENSION IF NOT EXISTS citext SCHEMA public;
COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';
-- -------------------------------------------------------------------------
-- ERROR: no pre-assigned OID for pg_type tuple "citext" (namespace:11 keyOid1:0 keyOid2:0) (oid_dispatch.c:650)  (seg1 10.219.66.151:6001 pid=23080) (oid_dispatch.c:650)
--  Line: 9
-- CREATE EXTENSION IF NOT EXISTS citext SCHEMA public

CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public;
COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';
-----------------------------------------------------------
-- ERROR: no pre-assigned OID for pg_proc tuple "digest" (namespace:11 keyOid1:0 keyOid2:0) (oid_dispatch.c:650)  (seg0 10.219.66.151:6000 pid=23932) (oid_dispatch.c:650)
--   Line: 17
-- CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA public

ALTER TABLE public."UserRequisites_GP_test_part" SET WITH (REORGANIZE=true) DISTRIBUTED BY ("UserId");  --- !!!
ALTER TABLE public.pxf_ch_test_trg SET WITH (REORGANIZE=true) DISTRIBUTED BY ("EventDate");             --- !!!!
ALTER TABLE public.user_requisites_gp_test SET WITH (REORGANIZE=true) DISTRIBUTED BY ("UserId");        --- !!!

COMMIT TRANSACTION;

Будучи вынесенными в отдельный  скрипт, и другой инструмент (Dbeaver) операторы выполняются нормально.
Временное решение проблемы такое -  формировать миграционые скрипты в pgCodeKeeper, выполнять в другом инструменте.

**Comment by AXEPOH** [comment]
Не получается воспроизвести
