### ISSUE TITLE
В Мастере сравнения при установленном фильтре неверно работает "Выбрать все" в Таблице сравнения

### ISSUE THREAD

**Issue by Evgeny-V-K** [pgcodekeeper/pgcodekeeper#144]
## Описание проблемы

1. Запускаю "Мастер сравнения" и сверяю проект (целевая схема) с БД (Исходная схема)
2. В дополнительных опциях отмечаю "Создать скрипт только из выбранных объектов в панели сравнения"
3. В "Таблице сравнения" применяю фильтр "Поиск по контейнеру" где указываю конец названия схемы PostgreSQL (Например: `_end`). Нужны две схемы с одинаковым концом в названии.
4. После применения фильтра в "Таблице сравнения" высвечиваются изменения этих двух схем в виде 9 строк. Вложенных строк (`INDEX`, `CONSTRAINT` и т. д.) нет.
5. Нажимаю "Выбрать все" и после выбора на панели сравнения в графе "Всего" указано 12. Хотя в "Таблице сравнения" я вижу только 9 объектов.
6. Нажимаю Finish и смотрю получившийся скрипт. В скрипте присутствуют лишние 3 изменения два `CONSTRAINT` и один `INDEX`. Лишние, потому что данные объекты не были отображены в отфильтрованном в "Таблице сравнения" списке.

## Примечание

Если не использовать "Выбрать все" и вручную прокликать все 9 строк, то в скрипте будут только данные 9 изменений. Что верно.

3 изменения были от таблицы, в названии которой тоже присутствует `_end`, но данная таблица находится в другой схеме PostgreSQL, в которой нет `_end`. То есть для этих трех строк уже без применения фильтра в поле контейнер отображается схема PostgreSQL и название таблицы. Но почему-то в "Таблице сравнения" по фильтру они не отображаются.

Хотелось бы, чтобы при нажатии на "Выбрать все" выбирались и формировались в скрипт только видимые в "Таблице сравнения" изменения. А то выбираешь одно, а в скрипте добавляются ненужные тебе изменения, которые сложно заметить взглядом.

**Comment by AXEPOH** [comment]
Исправлено в f76e6a5d6622915ba89c99aef945bb6ecc7113af
