### ISSUE TITLE
В  хелпе не описано значение параметра "SCHEMA"

### ISSUE THREAD

**Issue by mthread1** [pgcodekeeper/pgcodekeeper#147]
В  хелпе не описано значение параметра "SCHEMA".
Например, SOURCE  и DEST описано, но SCHEMA - отсутствует.

![изображение](https://github.com/user-attachments/assets/073460f6-d4ff-49f8-be91-e04173ac5a89)

**Comment by AXEPOH** [comment]
Поменяли SCHEMA на SOURCE в 01ce03f1b23de14a1ee4e675540894504fa49600
