### ISSUE TITLE
MSSQL: удаление столбца таблицы с default constraint

### ISSUE THREAD

**Issue by ZolotovAL** [pgcodekeeper/pgcodekeeper#148]
Есть БД DB1 с таблицей:

```
create table dbo.Tab (
	Id int not NULL identity(1,1) constraint PK_Tab primary key,
	AnyData nvarchar(50) NULL
)
```

В БД DB2 в этой таблице добавлен столбец DefData с default constraint:

```
create table dbo.Tab (
	Id int not NULL identity(1,1) constraint PK_Tab primary key,
	AnyData nvarchar(50) NULL,
	DefData nvarchar(50) not NULL constraint DF_Tab_DefData default('Test')
)
```

Если через pgcodekeeper-cli сформировать скрипт приведения DB2 к DB1:

pgcodekeeper-cli.bat --db-type MS -o script.sql -s "jdbc:sqlserver://...DB1..." -t "jdbc:sqlserver://...DB2..."

то в script.sql будет только команда на удаление столба DefData без удаления constraint DF_Tab_DefData:

```
ALTER TABLE [dbo].[Tab]
	DROP COLUMN DefData
GO
```

Возникает ошибка выполнения, т.к. сначала надо удалить constraint столбца. 
И дополнительно, лучше перестраховываться и в DROP COLUMN имя столбца также заключить в квадратные скобки.

**Comment by AXEPOH** [comment]
исправлено в 429d72ddb209cd762d1d5b56b5f44091f1f311d5
