### ISSUE TITLE
MSSQL версия не понимает конструкцию: set nocount, xact_abort on

### ISSUE THREAD

**Issue by volodin-aa** [pgcodekeeper/pgcodekeeper#149]
MSSQL версия не понимает в процедуре конструкцию
```sql
set nocount, xact_abort on
```

![image](https://github.com/user-attachments/assets/399aa66d-aad2-4ffb-9351-6d87639b4b0b)

**Comment by AXEPOH** [comment]
исправлено в d69233d92218d42075f95a015b1b815deb11db81
