### ISSUE TITLE
табуляция и окно сравнения кода - все табуляции удалены

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#16]
В окне сравнения кода компаратора заметил полное исчезновение символов табуляции.
Из-за этого весь текст сплюснут...
При этом в окне сравнения истории кода - пкм на файле - compare  with - local history - всё хорошо.

**Comment by asaushkin** [comment]
![2018-03-23 12_01_03-workspace - try_timestamp - empty sql - eclipse platform](https://user-images.githubusercontent.com/471575/37822644-15d8cd98-2e98-11e8-9c4b-fbc6fab0afe4.png)
![2018-03-23 12_01_32-workspace - try_timestamp_schema_public_function_f1 sql - eclipse platform](https://user-images.githubusercontent.com/471575/37822645-160425e2-2e98-11e8-9676-6e9d284798a1.png)

**Comment by AXEPOH** [comment]
https://github.com/pgcodekeeper/pgcodekeeper/commit/c8d2562f47ed3774270bd506318e8cb1f0aa1e8b
Исправлено, теперь используются настройки Eclipse.
