### ISSUE TITLE
Улучшение читабельности функций при возврата таблиц и внешего вида таблиц.

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#18]
Если функция возвращает таблицу, то сейчас все IN параметры и OUT параметры выстраиваются в очень длинную строку...
```
CREATE OR REPLACE FUNCTION message_getdetail(p_ids integer[]) RETURNS TABLE("IdMessage" integer, "MessageUid" character varying, "DatePublish" timestamp without time zone, "DateDelete" timestamp without time zone, "IdMessageType" integer, "Body" xml, "Number" character varying, "IdAnnulmentMessage" integer, "LockReason" character varying)
```
это трудно читать и поддерживать...
Предлагаю начать работы по форматированию кода в более читабельный вид:
```
CREATE OR REPLACE FUNCTION message_getdetail(p_ids integer[]) RETURNS TABLE(
"IdMessage"                  integer, 
"MessageUid"                 character varying, 
"DatePublish"                timestamp without time zone, 
"DateDelete"                 timestamp without time zone, 
"IdMessageType"              integer, 
"Body"                       xml, 
"Number"                     character varying, 
"IdAnnulmentMessage"         integer, 
"LockReason"                 character varying
```
такой же стиль форматирования предлагаю делать и для таблиц, которые сейчас не имеют табличного вида, что усложняет отделение имен колонок от их типов и других признаков (not null, default...)
Конечно же компаратор должен это понимать и  внутри себя для сравнения использовать канонический вид лучше конечно именно такой - табличный).

**Comment by asaushkin** [comment]
Овчинка выделки не стоит. Реализация сложная, а профит небольшой. Если хотите красивого возвращаемого значения, создайте пользовательский тип или выделенную таблицу и возвращайте его, а не "анонимную"

**Comment by sgrinko** [comment]
Не согласен.
Профит - это пользователи продукта
А ведь продукт создается для них!

**Comment by sgrinko** [comment]
Для упрощения этой реализации и многих других желательных возможностей вновь стоит задуматься об изменении стратегии работы компаратора.
Если код проекта деплоить предварительно во временную БД, а уже из нее получать канонический вид, то можно очень легко решить эту и много других хотелок.

**Comment by asaushkin** [comment]
Это значительно изменит существующую архитектуру приложения. Увеличит задержки при выполнении базовых операции при работе с БД, увеличит сложность работы с проектом для пользователя и сложность разработки, увеличит ошибки при работе с разными версиями БД. 

На текущий момент, подобный рефакторинг выглядит неоправданным.

**Comment by sgrinko** [comment]
> Это значительно изменит существующую архитектуру приложения. 
Согласен. Я обсуждал это с вами на самом начальном этапе, но к сожалению тогда Вы выбрали как раз самый сложный путь - самостоятельный синтаксический анализ исходного кода, а теперь когда требуется сделать профит на основе этого анализа, вы говорите что реализация слишком сложная.

>Увеличит задержки при выполнении базовых операции при работе с БД, 
согласен, что потребуется дополнительный шаг.

> увеличит сложность работы с проектом для пользователя 
вот здесь как раз для пользователя будет только лучше, так как он не будет ничего терять работая в проекте, а если он что-то создаст в БД, то компаратор втащит это в проекте, где разработчик уже сможет подрехтовать внешний вид и вуаля, компаратор после этого скорее всего не найдет различий! Так как синонимы, %TYPE, форматирование, ... - всё будет правильно понято!

> сложность разработки, увеличит ошибки при работе с разными версиями БД.
а вот этого как раз и не будет. 
Версия БД будет полностью синхронная с проектом, и pg_dump будет работать с одной  и той же версией PostgreSQL.
возможно не очень понятно написал:
в настройках проекта будет указано, под каким именем создать временную БД для компаратора . Именно в неё сначала будут выполнен деплой и из нее pg_dump получит канонический вид.
Понимаю, что возможно не все захотят, чтобы у них в кластере была такая "левая" БД. 
В таком случае можно слелать через docker, но оставьте это на DBA пусть пользователи сами решат как им лучше.

**Comment by asaushkin** [comment]
Это предложение - слишком большой костыль. Мы ориентируемся на форматирование кода постгресом. И сохраняем и отображаем код именно в таком виде, как это делает постгрес. 

Если в postgresql когда-нибудь появятся механизмы форматирования кода по предложенным правилам, то с высокой долей вероятности они могут оказаться и в кипере.

**Comment by sgrinko** [comment]
@asaushkin 
К сожалению в postgres напрочь отсутствует какое-либо форматирование и много чего еще тоже отсутствует...
Надеяться, что что-то измениться не приходится... длительное общение с разработчиками показало, что это проблема их не волнует совсем. Вся надежда была именно на ваш продукт.
