### ISSUE TITLE
нарушен порядок выкладки объектов в деплойном скрипте

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#19]
Сейчас выполняется провод кода функций до изменений в таблицах и вьюхах.
Проявляется проблема если включить проверку синтаксиса в функциях.
Конечно её можно выключить и проблема завуалируется... но считаю что всё же порядок в деплойном скрипте должен учитывать зависимости.

**Comment by sgrinko** [comment]
Alexander Levsha, [26.03.18 17:54]
перед этим стоят 2 большие задачи: парсинг и анализ тел функций

Сергей Гринько, [26.03.18 17:55]
я рад, что об этом никто не забыл и оно просто в очереди
хотя на мой взгляд, можно просто деплоить в таком порядке(на первое время)
1) типы
2) таблицы
3) вьюхи
4) функции
а сейчас почему-то функции стоят на 1 месте

Alexander Levsha, [26.03.18 17:56]
Деплой вьюх точно сломается без функций, а функции хотя бы можно заглушить.

Сергей Гринько, [26.03.18 17:57]
зависмость вьюх от функций - точно можно легко проверить
наооборот конечно сложнее :(
предлагаю такие зависимые функции (от вьюх, индексов...) всегда заглушать и ставить первыми, а все остальные функции помещать в конец и уже слушаться флажка
это не критично - просто пища для размышления...

**Comment by asaushkin** [comment]
Данное поведение запланировано by deign. Изменения порядка наката не планируются.

**Comment by sgrinko** [comment]
@asaushkin 
>Данное поведение запланировано by design. Изменения порядка наката не планируются.

Пожалуйста раскрой подробнее... почему скрипт который нельзя накатить на БД считается корректным.

**Comment by asaushkin** [comment]
Порядок наката и воркараунд (отключение проверки тела хп) взяты из дампа формируемого pg_dump'ом. Этот порядок и используем в качестве эталонного.

**Comment by Endeavourl** [comment]
Добавлю, что "воркэраунд" пгдампа сделан далеко неспроста, если подумать о количетстве возможностей зациклить граф зависимостей при учете зависимостей в телах функций.

**Comment by sgrinko** [comment]
Разрывать зацикливание конечно нужно через заглушку функций и в этом случае эти функции стоит проводить первыми.
Ребята основная цель которую я хотел бы получить - это на этапе разработки+деплоя знать, что написанный код корректен хотя бы синтаксически и я правильно указал поля,таблицы,вьюхи...
Поэтому  я включаю у себя в проекте галочку 
![default](https://user-images.githubusercontent.com/10084993/38192493-d05a8924-3675-11e8-953e-0ccd13969c03.png)
в этом плане если сделать так как я предложил - это минимальная боль для вас и хороший профит для DBA

> предлагаю такие зависимые функции (от вьюх, индексов... что легко по зависимостям узнать) всегда заглушать и ставить первыми, а все остальные функции помещать в конец и уже слушаться флажка.
