### ISSUE TITLE
генерация кода drop/create всех зависимых объектов таблицы

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#2]
В случае когда выполняется перестановка порядка полей (на этапе разработки очень частая процедура), то компаратор эту ситуацию обнаруживает но ничего не генерирует.
Необходимо в данном случае выполнять полное пересоздание таблицы и поэтому нужно сгенерировать весь необходимый для этого код.

**Comment by asaushkin** [comment]
Хорошая стартовая задача для того, кто хотел бы принять участие в проекте.

**Comment by AXEPOH** [comment]
Добавлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/1e9e08b533f5f8bde145f0852332b84736d190f9
