### ISSUE TITLE
окно сравнения кода отображает не весь код сравниваемого объекта

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#20]
у меня есть в БД и в проекте табличка. В БД есть 2 индекса:
```
    "idx_union_company_temp_id_company" btree (id_company)
    "idx_union_company_temp_ogrn_inn" btree (ogrn, inn)
```
в проекте есть:
```
CREATE INDEX idx_union_company_temp_ogrn_inn ON union_company_temp USING btree (ogrn, inn);
```
и вот как это показывает окошко компаратора:
![default](https://user-images.githubusercontent.com/10084993/38026669-aa143f00-3295-11e8-9d15-3e7e7391a04d.png)

что в проекте:
```
SET search_path = dbo, pg_catalog;

CREATE UNLOGGED TABLE union_company_temp (
	id_union_company integer DEFAULT nextval('union_company_temp_id_union_company_seq'::regclass) NOT NULL,
	id_region integer,
	id_company integer,
	id_firm_bankrupt integer,
	id_sro integer,
	id_firm_trade_org integer,
	id_sro_trade_place integer,
	id_trade_place integer,
	is_active boolean DEFAULT true NOT NULL,
	ogrn character varying(13),
	inn character varying(10),
	short_name character varying(512),
	full_name character varying(1024) NOT NULL
);

ALTER TABLE union_company_temp OWNER TO postgres;

-- TABLE union_company_temp GRANT

REVOKE ALL ON TABLE union_company_temp FROM PUBLIC;
REVOKE ALL ON TABLE union_company_temp FROM postgres;
GRANT ALL ON TABLE union_company_temp TO postgres;
GRANT ALL ON TABLE union_company_temp TO developer_group;
GRANT ALL ON TABLE union_company_temp TO deploy;
GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE union_company_temp TO public_group;

--------------------------------------------------------------------------------

CREATE INDEX idx_union_company_temp_ogrn_inn ON union_company_temp USING btree (ogrn, inn);
```
что в БД:
```
-- Table: union_company_temp

-- DROP TABLE union_company_temp;

CREATE UNLOGGED TABLE union_company_temp
(
  id_union_company serial NOT NULL,
  id_region integer,
  id_company integer,
  id_firm_bankrupt integer,
  id_sro integer,
  id_firm_trade_org integer,
  id_sro_trade_place integer,
  id_trade_place integer,
  is_active boolean NOT NULL DEFAULT true,
  ogrn character varying(13),
  inn character varying(10),
  short_name character varying(512),
  full_name character varying(1024) NOT NULL
)
WITH (
  OIDS=FALSE
);
ALTER TABLE union_company_temp
  OWNER TO postgres;
GRANT ALL ON TABLE union_company_temp TO developer_group;
GRANT ALL ON TABLE union_company_temp TO deploy;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE union_company_temp TO public_group;
GRANT ALL ON TABLE union_company_temp TO postgres;

-- Index: idx_union_company_temp_id_company

-- DROP INDEX idx_union_company_temp_id_company;

CREATE INDEX idx_union_company_temp_id_company
  ON union_company_temp
  USING btree
  (id_company);

-- Index: idx_union_company_temp_ogrn_inn

-- DROP INDEX idx_union_company_temp_ogrn_inn;

CREATE INDEX idx_union_company_temp_ogrn_inn
  ON union_company_temp
  USING btree
  (ogrn COLLATE pg_catalog."default", inn COLLATE pg_catalog."default");
```

**Comment by Endeavourl** [comment]
В сравнении в редакторе проекта мы отображаем только различия между объектами. Также отображается "корневой" объект (таблица) независимо от наличия различий.
Так сделано для соответствия логики отображения элементов в дерево с логикой отображения различающегося кода.

**Comment by sgrinko** [comment]
@Endeavourl вот это не понял: `Так сделано для соответствия логики отображения элементов в дереве` что это такое ?

**Comment by Endeavourl** [comment]
В дереве различающихся объектов над сравнением кода

**Comment by asaushkin** [comment]
В целом согласен с Сергеем. Для пользователя это поведение не очевидно. Нужно подумать, как сделать так, чтобы или было видно, что часть кода скрыта. Или уведомлять об этом пользователя.

**Comment by Endeavourl** [comment]
Возможно, тогда не показывать корневые объекты без изменений? Так будет лаконичнее, логичнее - все таки панель _различий_ в коде, и наверно проще сделать.

**Comment by sgrinko** [comment]
возможно, что лаконичнее и логичнее :) , однако тогда иметь кнопочку - показать весь код - очень хотелось бы.... на случай прям оттуда скопировать для неких нужд часть или весь код.
А разве не проще для вас просто всё содержимое файла-объекта показать ?
Я думал, что вы так и делаете... типа определение индекса лежит в файле с таблицей, значит берём весь файл и сравниваем весь целиком с его канонической версией...

**Comment by Endeavourl** [comment]
Даблкликом по различию можно открыть файл в проекте.

Отображение различий кода происходит не по файлам (которых вообще нет для JDBC), а для объектов, присутствующих в структуре "дерево различий" - отображаемых в таблице сверху.
До того, как в таблице не появились поддеревья для объектов TABLE, никакой склейки кода в сравнении вообще не было.
Для отображения сравнения с кодом всех вложенных элементов нужно во-первых найти все подходящие объекты, что неудобно. Во-вторых объектов и склеенного кода может стать очень много.

**Comment by sgrinko** [comment]
Хорошо, тогда может всё таки остановимся на понимании, что показываем корневой объект и все его подобъекты которые без него не имеют смысла, в данном случае это конечно таблица и весь её код :)
по другому всё же не очень понятно, почему на верхнем уровне различий кода мы видим только часть кода от всего объекта... пример неясности:
![default](https://user-images.githubusercontent.com/10084993/38196638-d9e0aa98-368c-11e8-963e-5394ac438789.png)

после описания таблицы есть 3 блока где нет различий, но они показаны!
а в самом коде объекта до начала изменений есть еще несколько индексов, в которых изменений нет, и они пропущены !

**Comment by Endeavourl** [comment]
Все выделенные выражения считаются частью таблицы, потому что они задают свойства ее объекта.  
Индексы же - отдельные объекты, просто хранимые в одном файле с таблицей.

**Comment by sgrinko** [comment]
на мой взгляд, индексы ничем не отличаются от других объектов в этом списке.
никто из них не может существовать сам по себе без таблицы!
поэтому считаю что лучше либо выводить всё, либо выводить только различия ну и само определение таблицы. Слегка спорным здесь конечно является определение свойства IDENTITY... но так как все же это выводится отдельным statement-ом то предлагаю и его относить к понятию - показывать только если есть отличия.
Мне конечно по душе когда все подобные вещи как PK, FK, CONSTRAINT, IDENTITY выводятся не отдельным statement-ом, а сразу в CREATE TABLE .... и таким образом попадут под понятие корневого объекта...
Права и индексы конечно сюда не попадают...
ребята, вообщем обсудите это, здесь желательно что-то изменить.

**Comment by AXEPOH** [comment]
Добавили опцию в 7d5377cc132fb599714784f59b317713187f1e52

**Comment by sgrinko** [comment]
Спасибо!
