### ISSUE TITLE
Сборщик подчеркивает truncate как ошибочный

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#21]
Коллеги,
создал обычный sql файл и вбил следующий код.
Сборщик пометил truncate как ошибочную команду...
```
create temporary table if not exists tmp
(
    source              character varying(50)   not null,
    bulk_schema         character varying(50)   not null,
    table_name          character varying(64)   not null,
    pkey                character varying(50)   not null,
    procedure           character varying(64)   not null,
    is_needupdate_allow boolean                 not null,
    job_number          smallint                not null,
    specialbatch        smallint                not null,
    list_columns_ins    character varying(2048) not null,
    list_columns_upd    character varying(2048) not null
);
--
truncate table tmp;
--
```
extraneous input 'truncate' expecting {<EOF>, ALTER, COMMENT, COMMIT, DELETE, DROP, INSERT, NOTIFY, REVOKE, SET, START, UPDATE, VALUES, CREATE, GRANT, SELECT, TABLE, WITH, '('}	dbo.checksync_tables.sql	/fedresurs/Post-Deployment/LookupTables	line 21	pgCodeKeeper SQL ошибка

![default](https://user-images.githubusercontent.com/10084993/39242293-3b6f15b2-4892-11e8-8fa2-098c810164f0.png)

ошибка в сборщике?

**Comment by Endeavourl** [comment]
Парсер не поддерживает truncate, добавим.

**Comment by Endeavourl** [comment]
исправлено в 98780f8af00df0865229df37ffe79b8366fee03e
