### ISSUE TITLE
Поддержка FDW

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#22]
Коллеги,
нужна поддержка в проекте вот таких команд:
```
CREATE SERVER IF NOT EXISTS mssql_ross
    FOREIGN DATA WRAPPER tds_fdw
    OPTIONS (servername 'name_server', port '1433', database 'MyDB', tds_version '7.1');

CREATE USER MAPPING IF NOT EXISTS FOR postgres SERVER mssql_ross OPTIONS (username 'Login', password 'password');

CREATE FOREIGN TABLE mssql_ross."ADDRESS"
   ("ID_ADDRESS" integer NOT NULL,
    "ID_REGION" integer NOT NULL,
    "POST_IND" numeric(6) NOT NULL,
    "ADDRESS" character varying(500) NOT NULL)
   SERVER mssql_ross
   OPTIONS (schema_name 'dbo', table_name 'ADDRESS');
```
![default](https://user-images.githubusercontent.com/10084993/39615354-4dcd60fe-4f7e-11e8-82cb-cc68ecb09369.png)

**Comment by Endeavourl** [comment]
исправлено в 98780f8af00df0865229df37ffe79b8366fee03e

**Comment by sgrinko** [comment]
Не все команды поддержаны...
Вот такие еще остались:
![default](https://user-images.githubusercontent.com/10084993/40726700-f2cb88a0-642e-11e8-9e59-cd72be30bbcf.png)

**Comment by AXEPOH** [comment]
Добавлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/7ef5d6375d9f74af79722947efd44a1249125d12
