### ISSUE TITLE
поддержка команд FTS (Full Text Search)

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#24]
Прошу внедрить поддержку следующих объектов:

CREATE/DROP/ALTER TEXT SEARCH PARSER ...
CREATE/DROP/ALTER TEXT SEARCH DICTIONARY ...
CREATE/DROP/ALTER TEXT SEARCH CONFIGURATION ...
CREATE/DROP/ALTER TEXT SEARCH TEMPLATE ...
![default](https://user-images.githubusercontent.com/10084993/40728631-37bfc4e0-6433-11e8-9f0e-d68e41631620.png)

**Comment by Endeavourl** [comment]
поддержка объектов добавлена в 40f428d9d3abb15f0d6df7b03667b3d812ba0eb4
