### ISSUE TITLE
OPERATOR -- не известный для pgcodekeeper объект

### ISSUE THREAD

**Issue by 4orbit** [pgcodekeeper/pgcodekeeper#29]
CREATE OPERATOR
pgcodekeeper об этом не знает и пишет в лог такое:
!ENTRY apgdiff 2 0 2018-10-05 15:20:08.767
!MESSAGE ANTLR Error:
dmp.sql line 47673:7 mismatched input 'OPERATOR' expecting {DOMAIN, EVENT, EXTENSION, FUNCTION, GLOBAL, INDEX, LANGUAGE, LOCAL, MATERIALIZED, PROCEDURAL, RECURSIVE, RULE, SCHEMA, SEQUENCE, SERVER, TEMP, TEMPORAR
Y, TEXT, TRANSFORM, TRIGGER, TRUSTED, TYPE, UNLOGGED, VIEW, COLLATION, CONSTRAINT, FOREIGN, OR, TABLE, UNIQUE, USER}

документация по OPERATOR — тут https://postgrespro.ru/docs/postgresql/9.6/xoper

**Comment by AXEPOH** [comment]
Добавлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/15932165d6b7db218a2a79fc035eaf5416a1a086
