### ISSUE TITLE
Обработка синонимов типов данных

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#3]
В PostgreSQL очень много разных типов данных.
Многие из них означают одно и тоже :)
Например: varchar и character varying, integer и int4, bigint и int8....
Однако на данный момент компаратор видит это как разные типы данных.
Необходимо научить его всем возможным синонимам (ну или хотя бы начать этот процесс).

**Comment by asaushkin** [comment]
Да, это правильное направление.

**Comment by Endeavourl** [comment]
added in 6b20b81673356ee26088498c161b2523b066e210
