### ISSUE TITLE
CREATE AGGREGATE и CREATE OPERATOR

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#31]
Уважаемые разработчики
прошу добавить поддержку операторов и агрегаций
CREATE/DROP/ALTER AGGREGATE
CREATE/DROP/ALTER OPERATOR

если создать CREATE OPERATOR то сейчас компаратор просто падает с сообщением: 
Ошибка при сравнении БД
Ошибка при чтении схемы БД через JDBC, ошибка произошла при обработке jdbc:finalizing antlr
null

CREATE AGGREGATE к таким последствиям не приводит

**Comment by Endeavourl** [comment]
ошибка с именем оператора исправлена в e65e6c5e6ace59996d0f3f251015c1d8f01f21fd

**Comment by sgrinko** [comment]
Спасибо! Работает. Задачку можно закрыть.

**Comment by Endeavourl** [comment]
сделали агрегатки тоже a0525104870706cca7c1663009be34f294efa9a1
