### ISSUE TITLE
типы данных из расширения postgis не поддерживаются

### ISSUE THREAD

**Issue by ildarg** [pgcodekeeper/pgcodekeeper#32]
Для таблица где есть столбцы с типами данных из расширения возвращается ошибка
Multiple markers at this line
- mismatched input 'NOT' expecting {INHERITS, PARTITION, TABLESPACE, WITHOUT, ON, WITH, ';'}
- mismatched input '(' expecting {EXCLUDE, GENERATED, CHECK, COLLATE, CONSTRAINT, DEFAULT, FOREIGN, NOT, NULL, PRIMARY, REFERENCES, UNIQUE, ',', ')', '['}

пример: 
my_point public.geography(Point,0) NOT NULL

**Comment by Endeavourl** [comment]
исправлено e62bf8570c6e6da2c7673ce939865a5d8cd6af4d
