### ISSUE TITLE
Проблема с длинными именами сервера в FOREIGN TABLE

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#33]
Не переносится в проект длинное наименование сервера из скрипта по созданию FOREIGN TABLE и как следствие теряется блок OPTIONS.
![scrin](https://user-images.githubusercontent.com/47561913/52637173-92fab780-2edf-11e9-9375-549b448eed84.png)

**Comment by Endeavourl** [comment]
исправлено 3f843746e0417139509b8d055431c260c7272c5f
выпустим со следующим релизом
