### ISSUE TITLE
Теряется TABLESPACE для CONSTRAINT

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#34]
**Так скрипт выглядит в PgAdmin:**

![image](https://user-images.githubusercontent.com/47561913/52774292-ebe85e00-304d-11e9-836e-0f23d1dcde69.png)

**А так в pgcodekeeper:**

![image](https://user-images.githubusercontent.com/47561913/52774349-09b5c300-304e-11e9-92ee-39bd55b45bf0.png)

**Comment by Endeavourl** [comment]
исправлено 297e8ee8560cda91190d6b321017248f92fb2652

**Comment by pavel-xa** [comment]
Для ограничение по первичному ключу теперь все отлично, но теперь конструкция USING INDEX TABLESPACE добавляется и для внешнего ключа. 
Ограничение по внешнему ключу не поддерживает USING INDEX TABLESPACE.
Встроенный парсер работает корректно.

Так скрипт выглядит в PgAdmin:

![image](https://user-images.githubusercontent.com/47561913/53467856-eab12b00-3a68-11e9-87a9-1b71496368c8.png)

А так в pgCodeKeeper:

![image](https://user-images.githubusercontent.com/47561913/53467966-5b584780-3a69-11e9-95ac-1e019a0593f7.png)

**Comment by AXEPOH** [comment]
исправлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/d75464755e18c392928f3b3e86777c3c4d6f45c4
