### ISSUE TITLE
Теряются индексы на родительской секционированной таблице

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#35]
**Так скрипт выглядит в PgAdmin:**
![image](https://user-images.githubusercontent.com/47561913/52779344-0116ba00-3059-11e9-8cce-e0cdb8d747e7.png)

**А так в pgCodeKeeper:**
![image](https://user-images.githubusercontent.com/47561913/52779464-43d89200-3059-11e9-9a48-8d5d04edb14f.png)

**Comment by Endeavourl** [comment]
исправлено d85f6c055bf921192526898fb0a0393f74d24b2f

**Comment by pavel-xa** [comment]
В последней версии pgCodeKeeper индексы на родительской таблице не теряются, т.о в сформированном скрипте миграции индексы создаются по родительским и дочерним таблицам.

Но скрипт создания индекса по родительской таблице в миграционном скрипте по очередности находится первым и создает индексы в том числе и по дочерним таблицам.
Далее идущие скрипты по дочерним таблицам уже падают с ошибкой.

![default](https://user-images.githubusercontent.com/47561913/53786270-3e6db980-3f2c-11e9-8909-f6b148040f68.png)
DROPы в пример добавил для чистоты эксперимента.

Проблемы можно избежать, если добавлять IF NOT EXISTS в подобные конструкции - [#40](https://github.com/pgcodekeeper/pgcodekeeper/issues/40)

**Comment by Endeavourl** [comment]
скорее, для создания индекса на родительской (или любой) таблице будем писать `ONLY table_name`

**Comment by AXEPOH** [comment]
Исправлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/79ce064cc8d32a4eb30f5e9fb923848a47c15f4b
