### ISSUE TITLE
Генерация избыточного кода для дочерней секционированной таблицы

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#36]
1. Здесь избыточный код по унаследованным от родительской таблицы значениям по-умолчанию

![image](https://user-images.githubusercontent.com/47561913/52838950-763fc900-3105-11e9-8481-79e5a1a80926.png)

2. Здесь в качестве различий указаны унаследованные от родительской таблицы ограничения после выполнения миграционного скрипта.

![image](https://user-images.githubusercontent.com/47561913/52840467-70001b80-310a-11e9-970b-e03131e9c6d4.png)

![image](https://user-images.githubusercontent.com/47561913/52839689-0ed74880-3108-11e9-8056-7cc639e9bb97.png)

**Comment by Endeavourl** [comment]
исправлено 4976cd0a15ac7c8a1f96d4f9802784c4d27b29aa

**Comment by AXEPOH** [comment]
В 1 пункте поведение соответствует pg_dump - у
![default_dump](https://user-images.githubusercontent.com/24290111/52954866-4c540400-339c-11e9-9faf-816e563da952.png)
