### ISSUE TITLE
Для секционированных таблиц создаются индексы для каждой дочерней таблицы

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#37]
Связано с https://github.com/pgcodekeeper/pgcodekeeper/issues/36 и https://github.com/pgcodekeeper/pgcodekeeper/issues/35.

Cейчас для секционированных таблиц генерируется создание индекса для каждой дочерней таблицы (выделил оранжевым). 
В PostgreSQL 11 достаточно создать индекс только на родительской (выделил зеленым), на дочерних он создается автоматически.

![image](https://user-images.githubusercontent.com/47561913/52861858-cab66900-3144-11e9-8b83-4fd81245209c.png)

**Comment by AXEPOH** [comment]
Поведение соответствует поведению pg_dump-a
![partition_dump](https://user-images.githubusercontent.com/24290111/52932840-2447af00-3362-11e9-9f07-542796bdd006.png)
