### ISSUE TITLE
Теряются индексы на материализованных представлениях

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#39]
Так в pgСodeKeeper:
![image](https://user-images.githubusercontent.com/47561913/53019030-e3848e80-3464-11e9-973b-19da1382aaeb.png)

так в БД:
![image](https://user-images.githubusercontent.com/47561913/53019112-1169d300-3465-11e9-8780-83c3ec8fb7b2.png)

**Comment by AXEPOH** [comment]
Исправлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/7c59d102b666ffea687a5e874b3d3e398041f121
