### ISSUE TITLE
Поддержка %TYPE в описаниях входных и выходных параметров

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#4]
Имена типов входных и выходных параметров можно указывать как ссылка на поле некой таблицы.
Ссылка на тип колонки записывается в виде имя_таблицы.имя_колонки%TYPE.
Иногда такое указание бывает полезно, так как позволяет создать функцию, независящую от изменений в определении таблицы.

**Comment by asaushkin** [comment]
Если бэкенд не считает сохранять информацию об этом в БД, то создавать "подпорку" для этого, пожалуй, не нужно. На мой взгляд, сомнительная хотелка.

**Comment by sgrinko** [comment]
@asaushkin это очень полезно если реализовать бизнес-процессы внутри БД.
При этом число функций начнет сильно расти и если не использовать %TYPE то при изменении типа поля нужно вручную везде это менять. Использование такой "подпорки" просто уменьшает число возможных ошибок, уменьшает время разработки и даёт понимание взаимосвязей.

**Comment by asaushkin** [comment]
Понимаю, что такая возможность есть. Могу лишь посоветовать в этих случаях использовать в качестве типов аргументов - таблицы, представления и пользовательские типы. Ну или уговорить разработчиков постгреса сохранять информацию о том, что тип является ссылкой на колонку таблицы. :)

**Comment by asaushkin** [comment]
Подождем пока постгрес будет сохранять эту информацию у себя.

**Comment by sgrinko** [comment]
Ну разве что самим написать патч... но они скорее всего даже это не пропустят.
Некоторые патчи ждут своего применения несколько лет!
Очень частая причина - они слишком объёмны (в смысле строк кода много).
Конечно надежда есть всегда, но она тает с каждым годом...
