### ISSUE TITLE
Добавление в миграционнные скрипты конструкций IF EXISTS/ IF NOT EXISTS

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#40]
Есть ли возможность добавить в миграционные скрипты конструкции IF EXISTS/ IF NOT EXISTS для CREATE, DROP, ALTER где это возможно ?

DROP TRIGGER [ IF EXISTS ]
CREATE VIEW [ IF NOT EXISTS ]
DROP VIEW [ IF EXISTS ]
CREATE MATERIALIZED VIEW [ IF NOT EXISTS ]
DROP MATERIALIZED VIEW [ IF EXISTS ]
ALTER TABLE [ IF EXISTS ] ADD [ COLUMN ] [ IF NOT EXISTS ] 
ALTER TABLE [ IF EXISTS ] DROP [ COLUMN ] [ IF EXISTS ]
CREATE INDEX [ IF NOT EXISTS ]
DROP INDEX [ IF EXISTS ]
и т.д.

Парсер сейчас тоже не понимает такое.

**Comment by Endeavourl** [comment]
исправлено в 7c59d102b666ffea687a5e874b3d3e398041f121

**Comment by pavel-xa** [comment]
Я правильно понимаю, что был доработан только парсер ?

Есть ли возможность добавлять подобные конструкции автоматом эти конструкции в миграционные скрипты ? 
Можно наверное сделать это по настройке.
1. Это поможет избежать потенциальных ошибок для случаев, когда объект был по какой-то причине ранее перенесен на целевую БД;
2. Позволит формировать миграционные скрипты, которые можно будет выполнять повторно.

**Comment by asaushkin** [comment]
Лучшим способом избежать этого, будет использование инструментов провижинга БД, таких как flyway и liquibase. Это убережёт и от многих других проблем, если вы вносите изменения в ваши БД в ручном режиме без поддержки версионирования.

**Comment by Fenoman** [comment]
Есть ли какие-то подвижки?

**Comment by Endeavourl** [comment]
Добавили фичу 94aa208d2dee800177b8abc8d69ba3729bd07732, выпустим в следующем релизе

**Comment by Fenoman** [comment]
О, вот это круто спасибо!!!
