### ISSUE TITLE
Добавление в миграционнные скрипты DROP перед CREATE

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#41]
В дополнение к https://github.com/pgcodekeeper/pgcodekeeper/issues/40

Для исключения потенциальных ошибок при установке миграционных скриптов на БД заказчика, на наш взгляд, было бы не лишним добавить в миграционные скрипты перед конструкциями:
**CREATE VIEW IF NOT EXISTS
CREATE MATERIALIZED VIEW IF NOT EXISTS
CREATE TRIGGER**
соответствующую создаваемому объекту конструкцию 
**DROP { VIEW | MATERIALIZED VIEW | TRIGGER } IF EXISTS**
независимо от наличия этих объектов в целевой БД.

Ошибочная ситуация без DROP может возникнуть в случае если объект по какой-то причине, например в рамках критического обращения, создался ранее на БД заказчика вручную, позже перенесен на БД разработки и там доработан. Были такие случаи на практике.

Добавление этой конструкции в скрипты дает гарантию того, что эти объекты в БД заказчика будут однозначно синхронизированы с БД разработки, а в случае триггера не упадут с ошибкой.

Можно реализовать в виде настройки проекта.

P.S. В целом инструмент pgCodeKeeper отличный, за что вам большое спасибо!
Когда можно ждать следующей версии (вероятно 5.4.0) и обновления версии в Marketplace Eclipse ?

**Comment by AXEPOH** [comment]
Спасибо за положительный отзыв.
Версии выходят с периодичность в 2 недели (чаще всего). Следующий релиз запланирован на 26.02.2019.
В Marketplace Eclipse всегда последняя версия.

**Comment by Fenoman** [comment]
Даже не просто отличный, а лучший что есть на рынке я бы сказал! Спасибо вам огромное. Это то что там нужно, мы в данный момент переходим с MS SQL на Postgres и раньше пользовались SSDT (хранение БД как проект SSDT в TFVC) и ваш инструмент прям находка. Вообще такое ощущение, что не многие задумываются о хранении кода БД в системе контроля версий и автоматическом формировании скриптов миграций. 
Предложенная доработка действительно очень важна и нужна!

**Comment by Endeavourl** [comment]
> Можно реализовать в виде настройки проекта.
Да, думаю можно сделать настройку для генерации drop if exists перед подходящими объектами

Обычно релизы происходят раз в 2 недели по вторникам. Но этот вторник скорее всего перенесется на следующий. 

спасибо за добрые слова :)

**Comment by Fenoman** [comment]
Есть ли какие-то подвижки?

**Comment by Endeavourl** [comment]
Добавили фичу 94aa208d2dee800177b8abc8d69ba3729bd07732, выпустим в следующем релизе

**Comment by Fenoman** [comment]
Просто отлично!!!
