### ISSUE TITLE
Для SEQUENCE не формируется миграционный скрипт по значению OWNED BY

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#42]
В случае  расхождения по значению OWNED BY для SEQUENCE 

![изображение](https://user-images.githubusercontent.com/47561913/54335342-b711fb80-4639-11e9-8bfd-67ddf4ffe33e.png)

формируется пустой миграционный скрипт

![изображение](https://user-images.githubusercontent.com/47561913/54335034-cf354b00-4638-11e9-90fc-d0ddd8ed2e8d.png)

Если SEQUENCE удалить с целевой базы, то скрипт формируется корректно

![изображение](https://user-images.githubusercontent.com/47561913/54335211-4ec31a00-4639-11e9-8087-727dafebdf79.png)

**Comment by Endeavourl** [comment]
Да, это известная старая проблема, для исправления которой нужно сильно/полностью переделывать алгоритм работы с зависимостями.

**Comment by Endeavourl** [comment]
удалось найти решение, исправлено в 503923d5cadb21e1d822d63f14242f165be5c287
