### ISSUE TITLE
11-я версия и DEFAULT

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#43]
Уважаемые разработчики, может быть уже пора (на дворе 11.2) сделать вместо вот этого:
——————
ALTER TABLE base.hershel_events
  ADD COLUMN hershel_event_stage_id smallint;

ALTER TABLE ONLY base.hershel_events
  ALTER COLUMN hershel_event_stage_id SET DEFAULT 2;

UPDATE ONLY base.hershel_events
  SET hershel_event_stage_id = DEFAULT WHERE hershel_event_stage_id IS NULL;

ALTER TABLE ONLY base.hershel_events
  ALTER COLUMN hershel_event_stage_id SET NOT NULL;
————————-
для 11 версии всего одну команду
ALTER TABLE base.hershel_events ADD COLUMN hershel_event_stage_id smallint not null default 2;
просто сейчас за этим приходится следить.... напрягает

да, теперь такая команда работает только на уровне метаданных, за милисекунды

главное чтобы всё проводилось 1-й командой. Тогда новая колонка добавляется и в сразу в метаданных прописывается DEFAULT, а все команды чтения кортежей читают данные из метаданных если нет такого поля в кортеже

**Comment by Endeavourl** [comment]
исправлено bc0a4f754eeab0d476045df07b51e191465ca71b
для старых версий тоже будет генериться одна команда, потому что сейчас нет возможности разделять генерацию по версиям и, в этих случаях с NOT NULL, мы бы все равно сгенерили бы там UPDATE, вместо которого обновлением данных сейчас займется ADD COLUMN ... DEFAULT
