### ISSUE TITLE
Комапаратор и GENERATED BY DEFAULT AS IDENTITY

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#45]
Версия кипера: 5.4.7
Всё таки есть проблемы с компаратором, хотя пока я не добрался ещё до неверного порядка `DROP/CREATE`  :)
Вот смотрите:
Исходная таблица:
```
CREATE TABLE dbo.union_person_pb_temp (
	id_union_person_pb integer NOT NULL,
	id_union_person integer NOT NULL,
	id_person_bankrupt integer NOT NULL
);
```
добавляем в проекте "GENERATED BY DEFAULT AS IDENTITY"
```
CREATE TABLE dbo.union_person_pb_temp (
	id_union_person_pb integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_union_person integer NOT NULL,
	id_person_bankrupt integer NOT NULL
);
```
компаратор различий не находит

**Comment by AXEPOH** [comment]
```GENERATED BY DEFAULT AS IDENTITY``` - синтаксический сахар, который сейчас не поддерживается и просто игнорируется

**Comment by Endeavourl** [comment]
Точно, я забыл, что основной синтаксис, в который конвертируется этот сахар, находится в ALTER TABLE 
`ALTER [ COLUMN ] column_name ADD GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ]`

**Comment by sgrinko** [comment]
Коллеги, но ведь PRIMARY KEY тоже синтаксичекский сахар. Его тоже можно реализовать на уровне ALTER TABLE...
Цель была - обнаружить изменения, выполнить деплой и закачать обратно в синтаксисе pg_dump.
Писать самому в синтаксисе ALTER TABLE:
```

**Comment by Endeavourl** [comment]
Мы посмотрим, просто в более низком приоритете, раз это не баг с функционалом таких сиквенсов.
Там, возможно, есть сложности с конвертацией этого синтаксиса в "не-сахарный", будем работать в зависимости от этого.

**Comment by AXEPOH** [comment]
Если ```Цель была - обнаружить изменения, выполнить деплой и закачать обратно в синтаксисе pg_dump.```, то можно воспользоваться функцией "Быстрого наката" в верхнем меню.
![image](https://user-images.githubusercontent.com/24290111/55390050-15e2da80-553f-11e9-99bb-7bb5d27d5e6b.png)

**Comment by sgrinko** [comment]
быстрое обновление это тоже игнорирует :)
но спасибо за подсказку, не знал, что это для этого :)

**Comment by Endeavourl** [comment]
исправлено в e4f6219a60e9216e29df822d287747b6d90b0d9f

**Comment by sgrinko** [comment]
Спасибо!
