### ISSUE TITLE
В скрипт попадают изменения для удаленного столбца по дочерним таблицам

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#47]
Вот как это выглядит:
Удаляем поля в родительской секционированной таблице
![image](https://user-images.githubusercontent.com/47561913/55463867-91599000-5602-11e9-9303-a136c1da094d.png)

Одно из полей имеет свойство DEFAULT и для него компаратор видит различие по каждой из дочерних таблиц
![image](https://user-images.githubusercontent.com/47561913/55464251-5a37ae80-5603-11e9-9116-7080ade0afae.png)

Т.о. получаем скрипт
![image](https://user-images.githubusercontent.com/47561913/55464770-7f78ec80-5604-11e9-9739-a2f3d1f3a634.png)

который падает с ошибкой
![image](https://user-images.githubusercontent.com/47561913/55464887-bbac4d00-5604-11e9-8fb9-a6c0a0a6fde5.png)

**Comment by Endeavourl** [comment]
Я так понимаю, решением будет дропы колонок для партишен таблиц делать тоже через ONLY?

**Comment by Endeavourl** [comment]
Исправлено 212e85e03103cba3094532f30205dbbe812c8f1c

**Comment by pavel-xa** [comment]
Такой вариант не подходит.

На последней версии:
![image](https://user-images.githubusercontent.com/47561913/57274689-a95e7c80-70a4-11e9-9f23-975feecc5d11.png)

**Comment by Endeavourl** [comment]
для партишен таблиц исправлено в e49ad8a389d0dcdac7e266a3026cfd6f9c5453a7
