### ISSUE TITLE
оптимизация при конкурентном изменении индексов

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#48]
Коллеги,
при коррекции индекса получаем вот такой код: 
(всё это имеет смысл если стоит галка создавать конкурентно в настройках)
```
DROP INDEX sfact.idx_message_body_subjects;

CREATE INDEX CONCURRENTLY idx_message_body_subjects ON sfact.message USING gin (dbo.xmlsubjects2text(body, id_message_type) public.gin_trgm_ops)
WHERE (id_message_type = ANY (ARRAY[28, 29, 30, 42, 47, 48, 51, 52, 53, 55]));
```
может быть стоит делать более умно !?
```
CREATE INDEX CONCURRENTLY tmpNNN_idx_message_body_subjects ON sfact.message USING gin (dbo.xmlsubjects2text(body, id_message_type) public.gin_trgm_ops)
WHERE (id_message_type = ANY (ARRAY[28, 29, 30, 42, 47, 48, 51, 52, 53, 55]));

begin;
DROP INDEX sfact.idx_message_body_subjects;
alter index sfact.tmpNNN_idx_message_body_subjects RENAME TO idx_message_body_subjects;
commit;
```
смысл в том, чтобы система жила без индекса крайне малый промежуток времени, а во время его построения работа с таблицей не блокировалась при этом. Таблицы ведь на проде часто велики, и построить по ним индекс без CONCURRENTLY просто нельзя из-за невозможности остановки работы системы.

**Comment by Endeavourl** [comment]
добавлено в 1986b7f9f6d1cd948c99d678e7aec3e7839038a5
