### ISSUE TITLE
Ошибка при добавлении NOT NULL на поле секционированной таблицы

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#49]
Добавили на одно из полей секционированной таблицы ограничение NOT NULL

![image](https://user-images.githubusercontent.com/47561913/56880776-c1138080-6a66-11e9-8031-a050ba9391e9.png)
генерится такой скрипт

![image](https://user-images.githubusercontent.com/47561913/56880846-0041d180-6a67-11e9-9de7-57f02cf83189.png)
который падает с ошибкой из-за ключевого слова ONLY.

**Comment by Endeavourl** [comment]
исправлено 4c8b84fc51fda28ed366b825433c70b5c1c2861a
