### ISSUE TITLE
Добавление PRE и POST скриптов в проект

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#5]
Предлагаю создать в корне проекта 2 папки и в каждой из них будет находиться файл скрипта
1) Pre-Deployment
Script.PreDeployment.sql
и
2) Post-Deployment
Script.PostDeployment.sql
—
смысл такой:
внутри этих скриптов мы будем писать код PRE и POST модификации БД между процессом компаратора схем.
Т.е.
- открываем транзакцию
- выполняем Script.PreDeployment.sql
- запускаем компаратор
- после выполнения полученного скрипт от компаратора выполняем Script.PostDeployment.sql
- закрываем (откатываем транзакцию)
Таким образом конечный скрипт, если его просто получить, будет состоять из 3-х частей
1.Script.PreDeployment.sql
2.скрипт компаратора
3.Script.PostDeployment.sql

В моей практике достаточно часто нужно перед тем как сравнить схемы сначала выполнить PRE модификации, а потом уже сравнивать.
Потом в конце проливать некие скрипт типа синхронизации справочников или обновления неких полей.

Таким образом в SourceControl будет лежать целостная структура от деплоя к деплою.
В этих папках DBA будут накапливать свои некие скрипты, которые будут вызываться изнутри PRE и POST файлов через простой метаязык
например
:r .\LookupTables\dboAGGREGATE_REPORT_TYPE.sql

где
:r - внешний скрипт
. - корневая папка проекта

процесс, что я описал желательно иметь в виде 2-х вариантов (наверное 2 отдельные вкладки с разным поведением)
1) как сейчас (то есть просто компаратор)
2) формирование скрипта PRE+компаратор+POST (проведение полноценного деплоя)
    можно это назвать - publish

**Comment by asaushkin** [comment]
Идея интересная, новый метаязык придумывать конечно-же не нужно, возможно стоит подумать о поддержке директивы `\i` в `psql`

**Comment by sgrinko** [comment]
директивы годятся любые конечно. 
использовать мнемоники совпадающие с синтаксисом psql думаю будет правильным :)

**Comment by sgrinko** [comment]
Уважаемые разработчики, если хоть какие-то подвижки в этом направлении?

**Comment by Endeavourl** [comment]
создали задачу в нашем внутреннем трекере чтобы не забыть, займемся, как будет подходящий момент

**Comment by sgrinko** [comment]
Спасибо

**Comment by Endeavourl** [comment]
Перечитывал эту задачу, и заметил, что не понял суть: речь идет о PRE/POST скриптах, выполняемых до/после генерируемых скриптов миграции, или до/после чтения схемы для сравнения БД?

**Comment by sgrinko** [comment]
Всё верно. 
Предлагаю реализовать механизм создания полноценных миграционных скриптов с учетом возможных Pre и Post скриптов. В VisualStudio это называется - Publish. Т.е. это отдельный интерфейс, или кнопка, позволяющая составить общий скрипт из 3 кусков. 
PRE скрипты в указанном порядке
скрипт компаратора
POST скрипты в указанном порядке

с точки зрения формирования скрипта компаратора можно предусмотреть вариант, когда PRE скрипты сначала выполняются на БД (внутри транзакции конечно) и потом уже на немного изменённой БД строится скрипт компаратора

**Comment by sgrinko** [comment]
Один из примеров применения скрипта Post
у нас нужно делать так, что в схеме для приложения у всех объектов должен быть отдельный владелец, не postgres.
Сам скрипт проливается от postgres, так как требуются superuser права для некоторых команд. Поэтому после того как пройдет скрипт компаратора, мне нужно выполнить кусочек кода в POST который поменяет владельца.
Ещё один вариант применения POST скрипта - проливка данных справочников оформленных как скрипт.
А вот PRE имеет более редкие применения.
К примеру туда можно добавить команду для бэкапа таблицы, с которой в скрипте компаратора выполняются критичные по правкам работы.

**Comment by sgrinko** [comment]
К примеру у меня сейчас в одном из проектов есть вот такие скрипты в POST
![изображение](https://user-images.githubusercontent.com/10084993/116223133-e6235280-a757-11eb-96f1-4befac1453a0.png)

На сейчас я конечно выполняю вручную все подобные скрипты при необходимости

**Comment by sgrinko** [comment]
Уважаемые разработчики, может быть есть возможность реализовать самый простой вариант этой фичи?
флажок  - publish, его лучше вмонтировать прямо рядом с текстом различия с
![изображение](https://user-images.githubusercontent.com/10084993/181087350-a3646945-ac07-4d0a-901a-86191efa92a9.png)

если включен, то формируется скрипт состоящий из 
PRE скрипты в указанном порядке
скрипт компаратора
POST скрипты в указанном порядке

**Comment by Endeavourl** [comment]
в каком-то виде сделали, скоро выпустим 8d173d21554b3487682ccc1872c9537ce5d19fad

если будут пожелания по доработке - лучше писать в новых issue
