### ISSUE TITLE
Изменение типа поля в таблице

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#50]
**Меняем тип поля с `int `на `text`**

![image](https://user-images.githubusercontent.com/47561913/58015516-27d70780-7b04-11e9-8b4e-6102c08bada4.png)

**тут все отлично**

![image](https://user-images.githubusercontent.com/47561913/58015776-c9f6ef80-7b04-11e9-927e-536cd3b391bb.png)

**Если было указано свойство `NOT NULL`**

![image](https://user-images.githubusercontent.com/47561913/58018920-db43fa00-7b0c-11e9-9cbe-880941d0320d.png)

**то тоже все нормально** 

![image](https://user-images.githubusercontent.com/47561913/58019008-1ba37800-7b0d-11e9-9181-dc10be5a6100.png)

**Но если у поля ранее было указано свойство `DEFAULT`**

![image](https://user-images.githubusercontent.com/47561913/58015902-15110280-7b05-11e9-9662-1a7c501a6eba.png)

**то получаем уже скрипт с `DROP COLUMN`:**

![image](https://user-images.githubusercontent.com/47561913/58018819-8902d900-7b0c-11e9-8941-aa586202b208.png)

**Comment by Endeavourl** [comment]
Не удается воспроизвести, у нас генерится так
```sql
ALTER TABLE ONLY public.t1
	ALTER COLUMN c3 DROP DEFAULT;

ALTER TABLE public.t1
	ALTER COLUMN c3 TYPE text USING c3::text; /* TYPE change - table: public.t1 original: integer new: text */

ALTER TABLE ONLY public.t1
	ALTER COLUMN c3 SET DEFAULT 'qwe'::integer;
```

**Comment by pavel-xa** [comment]
Проверил, суть именно в том, что у поля меняется тип и в качестве значения по-умолчанию была указана функция.
В других случаях работает корректно.

В примере использовал тестовую функцию
```
CREATE FUNCTION dbo.cf_user_id
(
) RETURNS integer
	STABLE
	LANGUAGE plpgsql
AS
$$
BEGIN
  RETURN 1::integer;
END
$$;
```

**Comment by Endeavourl** [comment]
разобрались, баг был в слишком широком условии спешал кейса зависимости от функции с дефолтными аргументами

исправлено c148905791520bd166602e1d7b6c0a5946ea7f1d
