### ISSUE TITLE
Изменение типа поля с установкой DEFAULT в секционированной таблице

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#51]
**Меняем тип поля с `int `на `text` с `DEFAULT`**

![image](https://user-images.githubusercontent.com/47561913/58079925-d0e03980-7bba-11e9-9a1b-4914f9d64819.png)

**получаем такой скрипт**

![image](https://user-images.githubusercontent.com/47561913/58080377-c70b0600-7bbb-11e9-8198-08fce7631313.png)

**который падает с ошибкой из-за очередности инструкций в скрипте**

![image](https://user-images.githubusercontent.com/47561913/58080070-21f02d80-7bbb-11e9-8954-d42b137d4890.png)

**Comment by Endeavourl** [comment]
для партишен таблиц исправлено в e49ad8a389d0dcdac7e266a3026cfd6f9c5453a7
