### ISSUE TITLE
Маппинг схемы и пользователя в postgres

### ISSUE THREAD

**Issue by sharkerr** [pgcodekeeper/pgcodekeeper#52]
Не нашел возможности настроить pgcodekeeper, так чтобы можно было бы указать разные названия схем и пользователя, для сравнения одних и тех же объектов. т.е.
имеется два стенда dev и test, название схем и пользователей на них отличается, а набор объектов один и тот же, имеется ли на данный момент какой-то маппинг объектов, чтобы при  получении изменений, объекты одной схемы не помечались, как удаленные?

**Comment by Endeavourl** [comment]
Нет, такой фичи нет и в планах тоже нет.
С различающимися пользователями, есть возможность выключить чтение владельцев и привилегий объектов в настройках pgCodeKeeper.
