### ISSUE TITLE
Поддержка Row-Level Security

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#53]
Row-Level Security поддерживается не полностью.

Включение/выключение политики безопасности для таблицы
`ALTER TABLE dbo.cs_custom_fields ENABLE ROW LEVEL SECURITY;`
поддерживается.

А вот сами политики
`CREATE POLICY user_policy ON dbo.cs_custom_fields USING (n_project = 4)`
не поддерживаются.

Можно ли добавить поддержку ?
pg_dump их выгружает.

**Comment by Endeavourl** [comment]
Думаю, можно будет заняться, объект не слишком сложный.

**Comment by AXEPOH** [comment]
Добавлено в 511f0763c8d650d8f5d6982b187050eab4ea6ac3
