### ISSUE TITLE
Неправильно скриптуются EXCLUDE ограничения 

### ISSUE THREAD

**Issue by Fenoman** [pgcodekeeper/pgcodekeeper#55]
Я добавляю в таблицу в БД такое ограничение:

```sql
ALTER TABLE public.some_table
	ADD CONSTRAINT xck_some_table_interval_overlaps EXCLUDE USING gist
		(
		column1 WITH =,
		daterange(d_date_begin, d_date_end, '[)'::TEXT) WITH &&
		)
		USING INDEX TABLESPACE ts_indexes
		DEFERRABLE INITIALLY DEFERRED;
```

То есть хочу повесить ограничение чтобы в разрезе column1 не было пересекающихся интервалов.
Однако, при сравнении базы с проектом формируется следующий скрипт для добавления в проект:

```sql
ALTER TABLE public.some_table
	ADD CONSTRAINT xck_some_table_interval_overlaps EXCLUDE USING gist 
        (
        column1 WITH =, 
        daterange(d_date_begin
	USING INDEX TABLESPACE ts_indexes;
```

1. Начисто игнорируется DEFERRABLE INITIALLY DEFERRED.
2. Конструкция  daterange почему-то обрезается и как следствие вся конструкция становится не валидной!

**Comment by Fenoman** [comment]
Так же, хотелось бы добавить, что у нас существуют и такие ограничения исключения:

```sql
ALTER TABLE some_table
	ADD CONSTRAINT xck_some_table_interval_overlaps EXCLUDE USING gist
		(
		column1 WITH =,
		tstzrange(d_date_begin, d_date_end, '[)') WITH &&
		)
		USING INDEX TABLESPACE ts_indexes
	        WHERE ( column2 <> 0 )
		DEFERRABLE INITIALLY DEFERRED;
```
Ключевое тут `WHERE ( column2 <> 0 )` то есть с фильтрацией!

**Comment by AXEPOH** [comment]
Исправлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/d5f95e06a176ac9a23231cbc8f2f335add171e6b

**Comment by Fenoman** [comment]
Класс, все теперь работает! Очень оперативно! Спасибо.
