### ISSUE TITLE
поддержка дополнительных языковых возможностей SQL при парсинге

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#56]
В версии 5.8.0 появился парсер SQL функций. Однако кое-что ещё надо доработать:

Следующий код даёт несколько ошибок:

```
CREATE OR REPLACE FUNCTION util.xpath_name_agg(p_body xml, p_node text, p_path_expr text, p_delimeter text = ', '::text) RETURNS text
    LANGUAGE sql IMMUTABLE PARALLEL SAFE COST 10.0
    AS $$
select string_agg(name_for_agg, p_delimeter order by rn) as name_agg
  FROM XMLTABLE(p_node PASSING p_body COLUMNS rn FOR ORDINALITY, name_for_agg text PATH p_path_expr) ;
$$;
```

function definition of xpath_name_agg line 5:16 extraneous input '(' expecting {<EOF>, ABORT, ABSOLUTE, ACCESS, ACTION, ADD, ADMIN, AFTER, AGGREGATE, ALSO, ALTER, ALWAYS, ASSERTION, ASSIGNMENT, AT, ATTACH, ATTRIBUTE, BACKWARD, BEFORE, BEGIN, BY, CACHE, CALL, CALLED, CASCADE, CASCADED, CATALOG, CHAIN, CHARACTERISTICS, CHECKPOINT, CLASS, CLOSE, CLUSTER, COLUMNS, COMMENT, COMMENTS, COMMIT, COMMITTED, CONFIGURATION, CONFLICT, CONNECTION, CONSTRAINTS, CONTENT, CONTINUE, CONVERSION, COPY, COST, CSV, CUBE, CURRENT, CURSOR, CYCLE, DATA, DATABASE, DAY, DEALLOCATE, DECLARE, DEFAULTS, DEFERRED, DEFINER, DELETE, DELIMITER, DELIMITERS, DEPENDS, DETACH, DICTIONARY, DISABLE, DISCARD, DOCUMENT, DOMAIN, DOUBLE, DROP, EACH, ENABLE, ENCODING, ENCRYPTED, ENUM, ESCAPE, EVENT, EXCLUDE, EXCLUDING, EXCLUSIVE, EXECUTE, EXPLAIN, EXTENSION, EXTERNAL, FAMILY, FILTER, FIRST, FOLLOWING, FORCE, FORWARD, FUNCTION, FUNCTIONS, GENERATED, GLOBAL, GRANTED, GROUPS, HANDLER, HEADER, HOLD, HOUR, IDENTITY, IF, IMMEDIATE, IMMUTABLE, IMPLICIT, IMPORT, INCLUDE, INCLUDING, INCREMENT, INDEX, INDEXES, INHERIT, INHERITS, INLINE, INPUT, INSENSITIVE, INSERT, INSTEAD, INVOKER, ISOLATION, KEY, LABEL, LANGUAGE, LARGE, LAST, LEAKPROOF, LEVEL, LISTEN, LOAD, LOCAL, LOCATION, LOCK, LOCKED, LOGGED, MAPPING, MATCH, MATERIALIZED, MAXVALUE, METHOD, MINUTE, MINVALUE, MODE, MONTH, MOVE, NAME, NAMES, NEW, NEXT, NO, NOTHING, NOTIFY, NOWAIT, NULLS, OBJECT, OF, OFF, OIDS, OLD, OPERATOR, OPTION, OPTIONS, ORDINALITY, OTHERS, OVER, OVERRIDING, OWNED, OWNER, PARALLEL, PARSER, PARTIAL, PARTITION, PASSING, PASSWORD, PLANS, POLICY, PRECEDING, PREPARE, PREPARED, PRESERVE, PRIOR, PRIVILEGES, PROCEDURAL, PROCEDURE, PROCEDURES, PROGRAM, PUBLICATION, QUOTE, RANGE, READ, REASSIGN, RECHECK, RECURSIVE, REF, REFERENCING, REFRESH, REINDEX, RELATIVE, RELEASE, RENAME, REPEATABLE, REPLACE, REPLICA, RESET, RESTART, RESTRICT, RETURNS, REVOKE, ROLE, ROLLBACK, ROLLUP, ROUTINE, ROUTINES, ROWS, RULE, SAVEPOINT, SCHEMA, SCHEMAS, SCROLL, SEARCH, SECOND, SECURITY, SEQUENCE, SEQUENCES, SERIALIZABLE, SERVER, SESSION, SET, SETS, SHARE, SHOW, SIMPLE, SKIP_, SNAPSHOT, SQL, STABLE, STANDALONE, START, STATEMENT, STATISTICS, STDIN, STDOUT, STORAGE, STRICT, STRIP, SUBSCRIPTION, SYSID, SYSTEM, TABLES, TABLESPACE, TEMP, TEMPLATE, TEMPORARY, TEXT, TIES, TRANSACTION, TRANSFORM, TRIGGER, TRUNCATE, TRUSTED, TYPE, TYPES, UNBOUNDED, UNCOMMITTED, UNENCRYPTED, UNKNOWN, UNLISTEN, UNLOGGED, UNTIL, UPDATE, VACUUM, VALID, VALIDATE, VALIDATOR, VALUE, VARYING, VERSION, VIEW, VIEWS, VOLATILE, WHITESPACE, WITHIN, WITHOUT, WORK, WRAPPER, WRITE, XML, YEAR, YES, ZONE, BETWEEN, BIGINT, BIT, BOOLEAN, CHAR, CHARACTER, COALESCE, DEC, DECIMAL, EXISTS, EXTRACT, FLOAT, GREATEST, GROUPING, INOUT, INT, INTEGER, INTERVAL, LEAST, NATIONAL, NCHAR, NONE, NULLIF, NUMERIC, OUT, OVERLAY, POSITION, PRECISION, REAL, ROW, SETOF, SMALLINT, SUBSTRING, TIME, TIMESTAMP, TREAT, TRIM, VALUES, VARCHAR, XMLATTRIBUTES, XMLCONCAT, XMLELEMENT, XMLEXISTS, XMLFOREST, XMLNAMESPACES, XMLPARSE, XMLPI, XMLROOT, XMLSERIALIZE, XMLTABLE, CROSS, FULL, INNER, JOIN, LEFT, NATURAL, RIGHT, AS, EXCEPT, FETCH, FOR, GROUP, HAVING, INTERSECT, INTO, LIMIT, OFFSET, ORDER, UNION, WHERE, WINDOW, ALIGNMENT, BASETYPE, BUFFERS, BYPASSRLS, CANONICAL, CATEGORY, COLLATABLE, COMBINEFUNC, COMMUTATOR, CONNECT, COSTS, CREATEDB, CREATEROLE, DESERIALFUNC, DISABLE_PAGE_SKIPPING, ELEMENT, EXTENDED, FINALFUNC, FINALFUNC_EXTRA, FINALFUNC_MODIFY, FORCE_NOT_NULL, FORCE_NULL, FORCE_QUOTE, FORMAT, GETTOKEN, HASH, HASHES, HEADLINE, HYPOTHETICAL, INIT, INITCOND, INTERNALLENGTH, JSON, LC_COLLATE, LC_CTYPE, LEFTARG, LEXIZE, LEXTYPES, LOCALE, LOGIN, MAIN, MERGES, MFINALFUNC, MFINALFUNC_EXTRA, MFINALFUNC_MODIFY, MINITCOND, MINVFUNC, MODULUS, MSFUNC, MSSPACE, MSTYPE, NEGATOR, NOBYPASSRLS, NOCREATEDB, NOCREATEROLE, NOINHERIT, NOLOGIN, NOREPLICATION, NOSUPERUSER, OUTPUT, PASSEDBYVALUE, PERMISSIVE, PLAIN, PREFERRED, PROVIDER, READ_ONLY, READ_WRITE, RECEIVE, REMAINDER, REPLICATION, RESTRICTED, RESTRICTIVE, RIGHTARG, SAFE, SEND, SERIALFUNC, SFUNC, SHAREABLE, SORTOP, SSPACE, STYPE, SUBTYPE_DIFF, SUBTYPE_OPCLASS, SUBTYPE, SUMMARY, SUPERUSER, TIMING, TYPMOD_IN, TYPMOD_OUT, UNSAFE, USAGE, VARIABLE, YAML, ALIAS, ASSERT, CONSTANT, DATATYPE, DEBUG, DETAIL, DIAGNOSTICS, ELSEIF, ELSIF, ERRCODE, EXIT, EXCEPTION, FOREACH, GET, HINT, INFO, LOG, LOOP, MESSAGE, NOTICE, OPEN, PERFORM, QUERY, RAISE, RECORD, RETURN, REVERSE, ROWTYPE, SLICE, SQLSTATE, STACKED, WARNING, WHILE, ';', ',', '*', '.', DOLLAR_NUMBER, Identifier, QuotedIdentifier}

function definition of xpath_name_agg line 5:24 mismatched input 'PASSING' expecting {<EOF>, CROSS, FULL, INNER, JOIN, LEFT, NATURAL, RIGHT, EXCEPT, FETCH, FOR, GROUP, HAVING, INTERSECT, INTO, LIMIT, OFFSET, ORDER, UNION, WHERE, WINDOW, ';', ',', '('}

function definition of xpath_name_agg line 5:54 mismatched input 'ORDINALITY' expecting {NO, SHARE, UPDATE}

**Comment by AXEPOH** [comment]
В парсер добавлен новый синтаксис https://github.com/pgcodekeeper/pgcodekeeper/commit/5de25b2b599cad30b32324e1b7e40f4e8c944bee
