### ISSUE TITLE
Дамп materialized view по создает WITH DATA, если мат вью заполнена данными.

### ISSUE THREAD

**Issue by Skoffer** [pgcodekeeper/pgcodekeeper#57]
```
SQL COMMAND: 
create materialized view t as select 1 with no data;

Pgcodekeeper - Database:
CREATE MATERIALIZED VIEW ignitestaging.t AS
	SELECT 1
WITH NO DATA;

Adding to project!

SQL COMMAND: 
refresh materialized view t;

Pgcodekeeper - Database:
CREATE MATERIALIZED VIEW ignitestaging.t AS
	SELECT 1
WITH DATA;
```

WITH DATA/ WITH NO DATA зависит от того, заполнена ли вью данными, а не от его ddl

**Comment by AXEPOH** [comment]
Команда `REFRESH MATERIALIZED VIEW` меняет состояние представления на c `WITH NO DATA` на `WITH DATA`. 

В https://github.com/pgcodekeeper/pgcodekeeper/commit/64e4009 добавлена генерация кода для изменения состояния без пересоздания представления.
