### ISSUE TITLE
Add a "Ignore privileges and owners of db objects" check box in the Diff Wizard

### ISSUE THREAD

**Issue by jrjsmrtn** [pgcodekeeper/pgcodekeeper#59]
When using the Diff Wizard, it may be useful to have an "Ignore privileges and owners of db objects" check box instead of having to go back to the pgCodeKeeper global preferences.

(and thanks for pgCodeKeeper, btw ;-)

**Comment by Endeavourl** [comment]
added with feb5fb8db022277aa5b17c623b37de2ea033dfc9
will be in the next release
