### ISSUE TITLE
Понимание default значений у описаний объектов

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#6]
У многих описаний объектов в виде скрипта есть default части, которые можно опустить или указать.
Сейчас при попытке их указать в явном виде это воспринимается как различие кода.
Наример:
при описании функций - COST 100, ROWS 1000, VOLATILE ...
при написании индексов если не указана явно сортировка, то понимается как ASC
и т.д.

К примеру, мы захотим навести порядок и написать в индексе asc
CREATE INDEX newsbreak_source_id_web_block_id_idx ON newsbreak USING btree (source_id, web_block_id asc);
и получим после этого :
DROP INDEX newsbreak_source_id_web_block_id_idx;
CREATE INDEX newsbreak_source_id_web_block_id_idx ON newsbreak USING btree (source_id, web_block_id asc);

а ведь по сути ничего не изменилось!

**Comment by asaushkin** [comment]
Реализация задачи может привести к потенциальным проблемам, т.к. дефолты у разных версий постгреса могут быть разные, а профит не очень весомым. Необходимо понимать востребованность этой фичи.

**Comment by sgrinko** [comment]
я работаю всегда от проекта. То есть у меня код в проекте главный.
Проблема сейчас связана с тем, что дефолтные значения не скриптуются в обратку... и таким образом получаются расхождения.
С этим связано все, что не скриптуется в обратку....
К сожалению меня разработчики самого потсгресса не слышат, так как они сами не работают как DBA, поэтому надежда только на подобные инструменты.

**Comment by asaushkin** [comment]
В любом случае, мы сохраняем именно так, как нам отдаёт постгрес информацию об этом объекте. Как я уже сказал ранее, отслеживать дефолтные значения объектов в разных версиях постгреса может представлять проблему поддержки разных версий постгреса.
