### ISSUE TITLE
Не учитывается зависимость таблицы от функции в значении по-умолчанию

### ISSUE THREAD

**Issue by pavel-xa** [pgcodekeeper/pgcodekeeper#60]
Есть таблица у которой в качестве значения по-умолчанию используется скалярная функция.

![изображение](https://user-images.githubusercontent.com/47561913/66812656-00ae2600-ef3c-11e9-9b1f-c09cab2a4556.png)
![изображение](https://user-images.githubusercontent.com/47561913/66811952-a791c280-ef3a-11e9-85dd-77c9d53a5363.png)

При изменении таблицы вместе с одновременным удалением этой функции генерится такой скрипт:

![изображение](https://user-images.githubusercontent.com/47561913/66812442-8f6e7300-ef3b-11e9-8268-d1163e5e3d3b.png)

который падает с ошибкой из-за того, что удаление функции происходит раньше, чем удаление таблицы.

![изображение](https://user-images.githubusercontent.com/47561913/66812499-aa40e780-ef3b-11e9-8673-6e2f538892f5.png)

P.S. Если изменение таблицы происходит без `DROP/CREATE TABLE`, то порядок корректный.

**Comment by Endeavourl** [comment]
проблема с такими зависимостями известна, недавно найден потенциальный фикс
выпустим в одном из ближайших релизов, посмотрим поможет ли в этом случае

**Comment by Endeavourl** [comment]
исправлено в 503923d5cadb21e1d822d63f14242f165be5c287 и b60a8faff025fdf95cb27bef7f2863f8773a85ba
