### ISSUE TITLE
Ignore Objects does not seem to be working

### ISSUE THREAD

**Issue by theldberg** [pgcodekeeper/pgcodekeeper#64]
I'm trying to do some compares of just a single schema across two databases. I've tried to use both black-list and white-list in the global settings but the result window always shows all schemas. 

(example attached) ![white list](https://user-images.githubusercontent.com/59620423/74060500-bef43000-49af-11ea-8cc4-42bc8e472f3a.PNG)

I've tried various other things with no luck:
1.) Setting up black or white list files on the database
2.) Setting up connection parameters to use a specific schemas

**Comment by Endeavourl** [comment]
Are you using Diff Wizard? We mostly use project workflow where ignore lists work fine and i guess we forgot to implement them into Diff Wizard.
We will add that functionality in the future relase.

**Comment by theldberg** [comment]
Yep, Diff Wizard directly to diff existing database deployments.

**Comment by Endeavourl** [comment]
fixed f2ab9674adb8d52ec161f3713701920f8ca995a5
We'll add it in the next release
