### ISSUE TITLE
Баг парсера - есть схема в проекте, но нет схемы в БД

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#67]
Уважаемые разработчики,
если завести новую схему в проекте и сослаться на неё из функции существующей схемы, 
то при сравнении схемы получаем ошибку:
 
![изображение](https://user-images.githubusercontent.com/10084993/75757929-4e3cfb00-5d44-11ea-8a74-6545e11e173d.png)

давайте сделаем опцию как показывать, явно или просто писать в консоль/error log

**Comment by AXEPOH** [comment]
Ожидаемое поведение.
Добавлена возможность скрывать сообщения об ошибках в 21bb864.
