### ISSUE TITLE
Поддержка типов SERIAL (синтаксический сахар)

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#7]
Типы данных smallserial, serial и bigserial не являются настоящими типами, а представляют собой просто удобное средство для создания колонок с уникальными идентификаторами (подобное свойству AUTO_INCREMENT в некоторых СУБД). В текущей реализации запись:

CREATE TABLE имя_таблицы (
имя_колонки SERIAL
);
равнозначна следующим командам:

CREATE SEQUENCE имя_таблицы_имя_колонки_seq;
CREATE TABLE имя_таблицы (
имя_колонки integer NOT NULL DEFAULT nextval('имя_таблицы_имя_колонки_seq')
);
ALTER SEQUENCE имя_таблицы_имя_колонки_seq OWNED BY имя_таблицы.имя_колонки;
То есть при определении такого типа создаётся целочисленная колонка со значением по умолчанию, извлекаемым из генератора последовательности. Чтобы в колонку нельзя было вставить NULL, в её определение добавляется ограничение NOT NULL. (Во многих случаях также имеет смысл добавить для этой колонки ограничения UNIQUE или PRIMARY KEY для защиты от ошибочного добавления дублирующихся значений, но автоматически это не происходит.) Последняя команда определяет, что последовательность «принадлежит» колонке, так что она будет удалена при удалении колонки или таблицы.

Имена типов serial и serial4 равнозначны: они создают колонки integer. Так же являются синонимами имена bigserial и serial8, но они создают колонки bigint.
И наконец, синонимами являются имена типов smallserial и serial2, но они создают колонку smallint.

Последовательность, созданная для колонки serial, автоматически удаляется при удалении связанной колонки. Последовательность можно удалить и отдельно от колонки, но при этом также будет удалено определение значения по умолчанию.

**Comment by asaushkin** [comment]
На текущий момент планов по представлению объектов БД псевдозаменителями нет. Устанавливаю "help wanted", будут желающие сделать это - милости прошу.

**Comment by sgrinko** [comment]
думаю, что эту issue можно закрыть... с  выходом identity полей надобность в поддержке этого синтаксиса отпала.
