### ISSUE TITLE
Изменение порядка столбцов и переливка данных

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#70]
Уважаемые разработчики!

очень не хватает интерфейса по переливке данных!!!

Прошу реализовать, это ведь не очень сложно, НО ОЧЕНЬ ПОЛЕЗНО!
На PROD контуре вещь очень нужная, так как там иногда надо менять порядок столбцов, но вот терять данные при этом очень не хочется :(

вместо:
`DROP TABLE public.table1;`
писать
`ALTER TABLE public.table1 RENAME TO table1_79FC;`

потом как и есть
`CREATE TABLE public.table1 ...`
`ALTER TABLE base.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ...`

потом
`insert into public.table1 (...)`
`select ... from public.table1_79FC;`

восстанвливаем PK
`ALTER TABLE public.table1 ADD CONSTRAINT table1_pkey PRIMARY KEY (...);`

```
-- переустанавливаем последовательность
DO $$ DECLARE v_id integer = (SELECT MAX(id)+1 FROM public.table1); 
BEGIN
  execute 'alter table public.table1 alter ... restart with ' || v_id || ';';
END
$$;
```
далее воссоздаём все объекты как есть и сейчас....

и в конце чистим за собой
`drop table public.table1_79FC;`

ну и конечно работа в транзакции помогает нам решать возможные проблемы.

**Comment by Endeavourl** [comment]
фича добавлена в 89ae85380f08938cf0c1084078d46e23cc842285
будет в следующем релизе

**Comment by sgrinko** [comment]
Отлично!
Спасибо, ждем!!!
