### ISSUE TITLE
Ошибки сравнения проекта и БД при вложенных комментариях /* ... */

### ISSUE THREAD

**Issue by Fenoman** [pgcodekeeper/pgcodekeeper#71]
Существует следующая проблема.
Вот у нас есть довольно большой блок кода, в котором если комментарии /* ... */ к примеру
```sql
/*
Выполняем вставку
*/
insert into t 
(pk, name)
select 1, '1';

и так далее...
```
Затем появляется необходимость временно закомментировать весь этот блок кода:
```sql
/*
/*
Выполняем вставку
*/
insert into t 
(pk, name)
select 1, '1';

и так далее...
*/
```
В самой базе все работает прекрасно! Однако при сравнении через pgcodekeeper такие объекты начинают вываливаться с ошибками вида:
```
extraneous input '*/' expecting '(', '<<', Identifier
```

Возможно ли исправление данной ошибки?

**Comment by AXEPOH** [comment]
Посмотрим, что можно сделать

**Comment by AXEPOH** [comment]
Исправлено в 1785da2

**Comment by Fenoman** [comment]
Спасибо! Теперь все отлично!
