### ISSUE TITLE
Расширение pgq

### ISSUE THREAD

**Issue by Fenoman** [pgcodekeeper/pgcodekeeper#72]
Столкнулись еще с такой проблемой, что схема **pgq** одноименного расширения не видна при сравнении проекта и базы! 
По сути это даже нормально, таблицы из этой схемы точно не нужны в проекте. Однако при этом мы используем в своих функциях функции из этой схемы (например ```pgq.get_batch_events```) и при сравнении их с проектом вываливаются ошибки:
```
jdbc:/pgq_consumers/cd_analyze_func line 112:35 Schema 'pgq' not found!
```

При этом триггерные функции, которые висят на таблицах никаких ошибок при сравнении не вызывают. 
Подскажите что можно с этим сделать и почему все же она видна при сравнении?

**Comment by Endeavourl** [comment]
Пока что можно выключить отображение ошибок при сравнении проекта в настройках программы или проекта.  
В дальнейшем будем пробовать подключить к анализу кода расширения, установленные в БД.

![image](https://user-images.githubusercontent.com/5260193/86459065-e9fc6900-bd2e-11ea-85f4-a5c49d21b49d.png)

**Comment by Fenoman** [comment]
Понял! Спасибо.

**Comment by AXEPOH** [comment]
Исправлено в e4329dd

**Comment by Fenoman** [comment]
Да, теперь все отлично. Спасибо!
