### ISSUE TITLE
pgcodekeeper.cli сбой если в сравниваемой функции есть analyse

### ISSUE THREAD

**Issue by hardstep33** [pgcodekeeper/pgcodekeeper#73]
использовании pgcodekeeper.cli крашится сравнение двух БД если в сравниваемой функции есть analyse - extraneous input 'analyse' expecting '(', '<<', Identifier. В функции создаются временные таблицы, индексируются и проводится analyse таблиц. Убираю строку с analyse и сравнение и миграция проходят успешно.

**Comment by Endeavourl** [comment]
исправлено в 8ebe2233eb454ebf8c370850f58fa1957c0bbb38
