### ISSUE TITLE
Diff по схемам БД указанным в currentSchema параметре jdbc урла

### ISSUE THREAD

**Issue by Link3699** [pgcodekeeper/pgcodekeeper#76]
Добрый день!

Используем cli инструмент для генерации diff DDL между базами данных. Однако у нас есть потребность сравнивать между БД отдельные схемы, а не всю БД в целом. Указание параметра `currentSchema` или `searchpath` в параметре jdbc коннекта к БД не помогло.

**Окружение:**

- pgcodekeeper-cli Version: 5.10.7.202008271451
- postgresql 11.0
- liquibase 4.3.1
- postgresql jdbc driver 42.2.19.jre7

**Пример команды:**
```commandLine
pgCodeKeeper-cli/pgcodekeeper-cli.sh jdbc:postgresql://url1:5432/dbname?searchpath=test_schema_1&user=****&password=******** jdbc:postgresql://url2:5432/dbname?searchpath=test_schema_1&user=****&password=****
```

Аналогичное использование liquibase с указанием `currentSchema` в jdbc коннекте показало diff для одной схемы:

```commandLine
java -jar liquibase-core-4.3.1.jar --classpath=postgresql-42.2.19.jre7.jar --changeLogFile=15_mydiff.sql --driver=org.postgresql.Driver --url=jdbc:postgresql://url1:5432/dbname?currentSchema=test_schema_1 --username=user --password=password --referenceUrl=jdbc:postgresql://url2:5432/dbname?currentSchema=test_schema_1 --referenceUsername=user --referencePassword=password diffChangelog
 ```

**Вопрос:**
Результирующий diff выводит DDL по всем схемам. Не подскажете есть ли возможность с использованием pgcodekeeper смотреть diff по определенной схеме?

**Comment by Endeavourl** [comment]
Добрый день, пропустил сообщение от гитхаба.
Аналогичная фича сейчас находится в разработке. Добавим возможность выборочной загрузки схем с помощью дополнительных списков, вроде текущих списков игнорирования различий объектов.

**Comment by Endeavourl** [comment]
Добавили возможность выборочной загрузки схем в релизе [6.1.0](https://github.com/pgcodekeeper/pgcodekeeper/releases/tag/v6.1.0)
