### ISSUE TITLE
Недочет при сравнении БД и проекта

### ISSUE THREAD

**Issue by Fenoman** [pgcodekeeper/pgcodekeeper#77]
При сравнении БД и проекта, есть различия, которые никак нельзя устранить. Все они связанные с вычисляемыми полями, вот пример:

![2021-06-21_17-35-35](https://user-images.githubusercontent.com/34582446/122780033-1fd78c00-d2b7-11eb-90e3-2fee7fddf3d9.png)

**Comment by Endeavourl** [comment]
Спасибо, посмотрим. при вытаскивании выражения из парсера теряется перенос строки, стоящий вначале.

**Comment by Fenoman** [comment]
Отлично! Спасибо.

**Comment by Endeavourl** [comment]
исправлено в 437f74c1bb73cd1fa8ee400b5498fdf977573627
выпустим в ближайшем релизе
