### ISSUE TITLE
Относительный путь к библиотеке в проекте

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#78]
Уважаемые разработчики,
есть вот такой файлик: 
`.dependencies `
в папке с проектом. В нём есть для подключаемой библиотеки указание полного пути к ней.
Полный путь это не есть хорошо, для работы в команде, так как предполагает в этом случае хранение этой библиотеки у всех разработчиков строго одинаково. Это затруднительно, так как кто-то может работать в Windows, а кто-то в Linux.

> Вопрос, относительно чего. У нас библиотеки подключаются хттп ссылками на зип файлы, ссылки одинаковые для всех. Либо в ридми проекта написать, какие библиотеки разработчику надо подключить перед использованием, и не коммитить . dependencies файл

У нас библиотека, это такой проект как и все другие и лежит также в source control просто в другой папке.
Поэтому относительный путь для нас актуален.
А вот сама корневая папка где разработчик хранит свою копию source control у всех разная

> не коммитить . dependencies файл

Это конечно решит проблему, но усложнит общую работу.
Лучше конечно иметь возможность указывать путь относительно текущего проекта в котором используется библиотека.

Есть ли возможность хранить путь к такой библиотеке относительно проекта в котором используется библиотека?

**Comment by AXEPOH** [comment]
Добавлено в 8bb607d7f7d19e083d0af235f408d0ad225a0140
