### ISSUE TITLE
Некорректная работа с SEQUENCE (не IDENTITY)

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#85]
Сейчас при изменении данных начала последовательности
```
CREATE SEQUENCE imp_marketing.seq_lnd_external_doc
	START WITH 805999008
...
```
кипер генерит такой код
```
ALTER SEQUENCE imp_marketing.seq_lnd_external_doc RESTART WITH 810659008;
```
команда `RESTART WITH` изменяет значение которое будет использоваться при следующей генерации номера функцией `nextval()`. Далее кипер читает значения для компаратора из системной таблицы `pg_sequences`. Но в этой таблице нет следующего номера для генерации. Само по себе это значение хранится в поле last_value скрытой таблицы:
```
select * from pg_class where oid = 'imp_marketing.seq_lnd_external_doc'::regclass
```
Все поля можно прочитать просто обратившись к последовательности как к таблице:
```
select last_value, log_cnt, is_called from imp_marketing.seq_lnd_external_doc;
```
Следующее значение с которым нужно сравнивать в компараторе получить можно по такой простой формуле:
```
select last_value + case when is_called then 1 else 0 end as last_value 
from imp_marketing.seq_lnd_external_doc;
```

Предлагаю, вместо `RESTART WITH` использовать команду `START WITH`, которая меняет именно начальное значение последовательности записанное в таблице `pg_sequences`.

**Comment by Endeavourl** [comment]
исправлено в 56ab3eee97d235f2c39aa9dbc317f5acb661ce14
