### ISSUE TITLE
FOREIGN TABLE и построение скрипта

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#88]
Сейчас при попытке добавить/удалить новое поле в описании такой таблицы приводит к тому, что генерируется скрипт по переливке данных (соответсвующий флажок конечно включен).
Для таких таблиц это недопустимо. 
Наверное для них лучше идти по пути DROP/CREATE
Спасибо.

**Comment by AXEPOH** [comment]
исправлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/64717b6f3f5bb75cf16f0f7ea88f012f63744014
