### ISSUE TITLE
Переливка секционированных таблиц - ERROR

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#89]
Добрый день!

На текущий момент некорректно реализован скрипт переливки секционированных таблиц.
Исходная таблица:
```
CREATE TABLE marts_marketing.t_queue_contract_vln_part (
	violation_type_id 	bigint not null,
	contract_id 		bigint
)
PARTITION BY LIST (violation_type_id);

CREATE TABLE marts_marketing.t_queue_contract_vln_part_vln72 PARTITION OF marts_marketing.t_queue_contract_vln_part
FOR VALUES IN ('72');
CREATE TABLE marts_marketing.t_queue_contract_vln_part_vln107 PARTITION OF marts_marketing.t_queue_contract_vln_part
FOR VALUES IN ('107');
CREATE TABLE marts_marketing.t_queue_contract_vln_part_vln108 PARTITION OF marts_marketing.t_queue_contract_vln_part
FOR VALUES IN ('108');
```
внёс правки в центральную таблицу:
```
CREATE TABLE marts_marketing.t_queue_contract_vln_part (
	row_id				bigint not null,
	violation_type_id 	bigint not null,
	contract_id 		bigint
)
PARTITION BY LIST (violation_type_id);

ALTER TABLE marts_marketing.t_queue_contract_vln_part ALTER COLUMN row_id ADD GENERATED ALWAYS AS IDENTITY (
	SEQUENCE NAME marts_marketing.t_queue_contract_vln_part_row_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);
--------------------------------------------------------------------------------
ALTER TABLE marts_marketing.t_queue_contract_vln_part
	ADD CONSTRAINT t_queue_contract_vln_part_pkey PRIMARY KEY (violation_type_id, row_id);
```
Скрипт миграции создался ошибочный.

Сейчас общая структура скрипта переливки такая:
- удаление/переименовывание всех зависимых объектов
- создание новой версии центральной таблицы
- заливка данных в центральную таблицу из старой центральной таблицы
- создание новой секции
- заливка данных в новую секцию из старой

1. ошибка
Проблема сейчас в том, что на этапе работы с центральной таблицей в переливке участвуют ВСЕ данные всех ранее существующих секций, которых на данных момент ещё нет в новой версии этой секционированной таблицы.
Мы получаем подобную ошибку:
```
ERROR:  no partition of relation "t_queue_contract_vln_part" found for row
DETAIL:  Partition key of the failing row contains (violation_type_id) = (72).
```
Нужно добавить ключевое слово ONLY при работе с секционированными таблицами.
В этом случае при обработке последовательно центральной таблицы и её секций мы также последовательно перельём данные без ошибок.
Также как вариант, (мне это больше нравится), сразу воссоздать всю новую структуры новой секционированной таблицу до начала переливки данных центральной таблицы. В этом случае генерировать код переливки каждой секции не нужно!

2. ошибка
И ещё один момент.
При работе с секциями я получил переливку данных секций без указания полей, т.е код вот такой:
```
CREATE TABLE marts_marketing.t_queue_contract_vln_part_vln107 PARTITION OF marts_marketing.t_queue_contract_vln_part
FOR VALUES IN (107);

INSERT INTO marts_marketing.t_queue_contract_vln_part_vln107()
SELECT  FROM marts_marketing.t_queue_contract_vln_part_vln107_9505cf7eb6e6435f8af8ba0859c3a0c9;

DROP TABLE marts_marketing.t_queue_contract_vln_part_vln107_9505cf7eb6e6435f8af8ba0859c3a0c9;
```

3. ошибка
При удалении центральной таблицы, происходит удаление и всех скопированных секций.
```
DROP TABLE marts_marketing.t_queue_contract_vln_part_5a7991dc5301423698bf59af4d208127;
```
Таким образом, на этапе копирования секции копии данных уже нет!
```
ERROR: relation "marts_marketing.t_queue_contract_vln_part_vln72_be2670e6a849467fa2008f5ec74c2dc" does not exist
SQL state: 42P01
```
Удаление объектов должно быть после переливки всех секций.
Также удаление объектом секционированной таблицы нужно выполнять или от секций к центральной таблице или просто центральную таблицу.

полный код скрипта:
[2022-11-07_08_36_43_migration.sq.zip](https://github.com/pgcodekeeper/pgcodekeeper/files/9948605/2022-11-07_08_36_43_migration.sq.zip)

**Comment by sgrinko** [comment]
Дополнительно хотел бы отметить, что переливка из старой секции в текущую новую, как сейчас реализовано, будет давать сбой при указании GENERATED ALWAYS AS IDENTITY для центральной таблицы. Так как авто-генерация нового  значения будет срабатывать только при вставке в центральную таблицу. 
Если же указывать GENERATED BY DEFAULT AS IDENTITY, то для каждой секции нужно вручную создавать команду:
```
alter table <таблица секции> alter <колонка> set default nextval('<имя SEQUENCE>');
```
Поэтому мне больше нравится вариант, когда мы воссоздаём сразу всю новую структуры новой секционированной таблицу до начала переливки данных центральной таблицы и потом используем всего 1 запрос для переливки старой центральной таблицы в новую центральную таблицу.

**Comment by AXEPOH** [comment]
Исправлено в 40f476f

**Comment by sgrinko** [comment]
Ура!
Спасибо!
Ждём новую версию
