### ISSUE TITLE
Генерация кода view и скобки

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#9]
Коллеги, при генерации кода view расставляется много скобочек...
```
   FROM ((((((publisher p
     LEFT JOIN individual_entrepreneur ie ON ((ie.id_individual_entrepreneur = p.id_individual_entrepreneur)))
     LEFT JOIN company c ON ((c.id_company = p.id_company)))
     LEFT JOIN appraiser a ON ((a.id_appraiser = p.id_appraiser)))
     LEFT JOIN foreign_system fs ON ((fs.id_foreign_system = p.id_foreign_system)))
     LEFT JOIN person ps ON ((ps.id_person = p.id_person)))
     LEFT JOIN non_resident_company nr ON ((nr.id_non_resident_company = p.id_non_resident_company)));
```
так генерит дамп pg_dump. Лучше бы так как генерит код вызов pg_get_viewdef с pretty=true, (так это делает psql/pgadmin).
Предлагаю сделать так, чтобы можно было по настройке отказаться от совместимости с pg_dump и выводить код view в стиле psql.

**Comment by AXEPOH** [comment]
Добавлено в https://github.com/pgcodekeeper/pgcodekeeper/commit/4e45f689c4945bfa38a92a3881d01fcf709c73ec
