### ISSUE TITLE
Error: column "datlastsysoid" not exists

### ISSUE THREAD

**Issue by AndreyKotofotoff** [pgcodekeeper/pgcodekeeper#90]
`SELECT datlastsysoid::bigint FROM pg_catalog.pg_database pd
`
[42703] Error: column "datlastsysoid" not exists
[PostgreSQL_15_Beta_1_New_Features_en_20220524-1.pdf](https://h50146.www5.hpe.com/products/software/oe/linux/mainstream/support/lcc/pdf/PostgreSQL_15_Beta_1_New_Features_en_20220524-1.pdf)
page18
![image](https://user-images.githubusercontent.com/15908484/202300930-1ba87ce5-dda3-4667-9a7d-7c89b6e57b02.png)

PostgreSQL version
PostgreSQL 15.0 (Debian 15.0-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

![image](https://user-images.githubusercontent.com/15908484/202301253-02694e3f-33a7-4fc1-a330-3a7fbeb38799.png)

**Comment by AXEPOH** [comment]
fixed in [7.0.0](https://github.com/pgcodekeeper/pgcodekeeper/releases/tag/v7.0.0)

**Comment by AndreyKotofotoff** [comment]
CLI 7.0.1

**Comment by AxelCat** [comment]
> CLI 7.0.1
> 
> @AXEPOH

Судя по стектрейсу, это не 7.0.1. Попробуйте заново скачать  7 версию

**Comment by AndreyKotofotoff** [comment]
Реально, 6.2.0 версия зависла. 
CI/CD подвел, не скачал новый подготовленный образ с версией 7.0.1.

Все ок, Прошу прощения.!
Хорошего дня)
