### ISSUE TITLE
FOREIGN TABLE и изменение типа колонки

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#91]
Сейчас если изменить тип колонки, то при построении скрипта получаем такой код:
```
ALTER FOREIGN TABLE scan_2021.doc_head
  ALTER COLUMN content TYPE bytea USING content::bytea; /* ТИП колонки изменился - Таблица: scan_2021.doc_head оригинал: text новый: bytea */

ERROR: "doc_head" is not a table
```
Я предлагаю для таких таблиц реализовывать стратегию drop/create

**Comment by AXEPOH** [comment]
USING не поддерживается в FOREIGN TABLE, исправлено в 0dfea01d48c5ea18f5fc5bdcd9e8db55fdbdf826

**Comment by sgrinko** [comment]
Спасибо!
