### ISSUE TITLE
Field with name "merge" brokes syncronization

### ISSUE THREAD

**Issue by ViktorEgorov** [pgcodekeeper/pgcodekeeper#93]
Databse field with name "merge" brokes syncronization.
Just add to any table field with this name 
![image](https://user-images.githubusercontent.com/7499726/213483757-19708ce8-6e58-472b-afc2-d8e77b8ca617.png)

Solution is - to enclose the field name in quotes
![image](https://user-images.githubusercontent.com/7499726/213484410-ba738f97-ae6e-4051-a30b-008e1244ab4b.png)
But it can be rewrited back on the next syncronization.

Maybe, there is the way to force quotes around all field names?

**Comment by AXEPOH** [comment]
fixed in 6da340a1f979022f85d725abb6cac20c89cb0239

**Comment by ViktorEgorov** [comment]
Thank you that you fixed it so fast!
And how long it will take to update Eclipse extension?

**Comment by AXEPOH** [comment]
We'll try to release it next week.
