### ISSUE TITLE
Ошибка pgCodeKeeper при сравнении функции с VARIADIC

### ISSUE THREAD

**Issue by volodin-aa** [pgcodekeeper/pgcodekeeper#96]
Ошибка pgCodeKeeper 7.3.0 при сравнении функции в проекте с БД:
```sql
CREATE OR REPLACE FUNCTION public.f(a text, b text = NULL::text, VARIADIC c text[] = null::text[]) RETURNS text
    LANGUAGE plpgsql
    AS $$
begin
end;
$$;
```

pgCodeKeeper не правильно отображает сигнатуру функции в БД:

![Pasted image 20230322192343](https://user-images.githubusercontent.com/5697239/226976629-6e312f8b-b770-45f2-80c6-65925148a8a6.png)

**Comment by AXEPOH** [comment]
Исправлено в 868e4b6e0b90ba67d86156df124fa83c783d7969
