### ISSUE TITLE
Удаление секции целиком в проекте - скрипт из компаратора неверен

### ISSUE THREAD

**Issue by sgrinko** [pgcodekeeper/pgcodekeeper#97]
Добрый день,
Использую версию 7.3 (windows)

обнаружил проблему в построении скрипта компаратором в следующем случае:

Создаём в БД:

```
CREATE TABLE public.t_queue (
	row_id				bigint not null,
	violation_type_id 	bigint not null,
	contract_id 		bigint
)
PARTITION BY LIST (violation_type_id);

ALTER TABLE public.t_queue ALTER COLUMN row_id ADD GENERATED ALWAYS AS IDENTITY (
	SEQUENCE NAME public.t_queue_row_id_seq
	START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
);

--------------------------------------------------------------------------------

ALTER TABLE public.t_queue
	ADD CONSTRAINT t_queue_pkey PRIMARY KEY (violation_type_id, row_id);

CREATE TABLE public.t_queue_default PARTITION OF public.t_queue
DEFAULT;

CREATE TABLE public.t_queue_part1 PARTITION OF public.t_queue
FOR VALUES IN ('72');

CREATE TABLE public.t_queue_part2 PARTITION OF public.t_queue
FOR VALUES IN ('108');

CREATE TABLE public.t_queue_part3 PARTITION OF public.t_queue
FOR VALUES IN ('107');

CREATE INDEX t_queue_mart_contract_id_idx ON public.t_queue USING btree (contract_id);
```

Т.е. мы имеем секционированную таблицу с 3-мя секциями и 1 default секцией.
На секционированной таблице есть PK и 1 дополнительный индекс.

Портируем это в проект.

Теперь удаляем 1 секцию, например default секцию. 
Делаем это в проекте просто удаляя файл с описанием секции - "t_queue_default.sql"
Запускаем сравнение и генерим скрипт:

```
SET TIMEZONE TO 'UTC';

SET check_function_bodies = false;

START TRANSACTION;

SET search_path = pg_catalog;

-- HIDDEN: Object public.t_queue_default_contract_id_idx of type INDEX (action: DROP, reason: object cannot be dropped)

-- DEPCY: This INDEX depends on the INDEX: public.t_queue_default_contract_id_idx

DROP INDEX public.t_queue_mart_contract_id_idx;

DROP TABLE public.t_queue_default;

CREATE INDEX t_queue_mart_contract_id_idx ON ONLY public.t_queue USING btree (contract_id);

COMMIT TRANSACTION;
```

Этот скрипт делает некорректные изменения в БД.
Команда `DROP INDEX public.t_queue_mart_contract_id_idx;` выполняет удаление индекса на основной таблице и при этом движок БД выполнит удаление индекса на всех секциях также.
Команда `CREATE INDEX t_queue_mart_contract_id_idx ON ONLY public.t_queue USING btree (contract_id);` создаст индекс ТОЛЬКО на основной таблице.
Таким образом у нас после выполнения этого кода на оставшихся секциях не будет индекса. Индекс будет только на основной таблице.

Ожидался скрипт вот такой:

```
SET TIMEZONE TO 'UTC';

SET check_function_bodies = false;

START TRANSACTION;

SET search_path = pg_catalog;

DROP TABLE public.t_queue_default;

COMMIT TRANSACTION;
```

**Comment by AXEPOH** [comment]
исправлено в a058dcc5ddb58ec04ef10bf5cf3fcd50d1fba524
